# Custom Synthetic Test Data Generation for RAG Evaluation

> 本 Notebook 演示：**从原始文档自动生成 RAG 评测集**，并用 Ragas 指标对比两种生成方式的效果。

## 整体流程

```
原始文档 → 切分 Chunk → 合成 QA 测试集 → 搭建 RAG → Ragas 评估
                              ├─ Ragas TestsetGenerator（官方）
                              └─ 自定义 LLM 逐 Chunk 生成（可控）
```

## 前置要求

- Python 3.10+
- `.env` 中配置 `OPENAI_API_KEY`、`GOOGLE_API_KEY`（Embedding）
- 主要依赖：`ragas`、`langchain`、`datasets`、`faiss-cpu`

---

## Part 1 — 环境配置

初始化 LLM、Embedding 模型，并包装为 Ragas 可用的接口。Embedding 使用**本地文件缓存**，避免重复调用 API。

In [2]:
!python --version

Python 3.11.0

In [5]:
from dotenv import load_dotenv

load_dotenv(override=True)

True

In [6]:
from langchain_openai import ChatOpenAI

llm = ChatOpenAI(model="gpt-4.1-nano")

In [7]:
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_google_genai import GoogleGenerativeAIEmbeddings

embeddings = GoogleGenerativeAIEmbeddings(model="models/gemini-embedding-001")

In [9]:
embeddings

GoogleGenerativeAIEmbeddings(client=<google.ai.generativelanguage_v1beta.services.generative_service.client.GenerativeServiceClient object at 0x000002B2BA262350>, async_client=None, model='models/gemini-embedding-001', task_type=None, google_api_key=SecretStr('**********'), credentials=None, client_options=None, base_url=None, transport=None, request_options=None)

In [8]:
from langchain_google_genai import GoogleGenerativeAIEmbeddings
from langchain_classic.storage import LocalFileStore
from langchain_classic.embeddings import CacheBackedEmbeddings

store = LocalFileStore("embedding_cache/")
if  isinstance(embeddings, GoogleGenerativeAIEmbeddings):
    name_space = embeddings.model
else:
    name_space = embeddings.model_name

cached_embedding = CacheBackedEmbeddings.from_bytes_store(
    underlying_embeddings=embeddings,
    document_embedding_cache=store,
    namespace=name_space
)

d:\Programs\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\langchain_classic\embeddings\cache.py:58: UserWarning: Using default key encoder: SHA-1 is *not* collision-resistant. While acceptable for most cache scenarios, a motivated attacker can craft two different payloads that map to the same cache key. If that risk matters in your environment, supply a stronger encoder (e.g. SHA-256 or BLAKE2) via the `key_encoder` argument. If you change the key encoder, consider also creating a new cache, to avoid (the potential for) collisions with existing keys.
  _warn_about_sha1_encoder()

In [10]:
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper

generator_llm = LangchainLLMWrapper(llm)
generator_embeddings = LangchainEmbeddingsWrapper(cached_embedding)

---

## Part 2 — 加载语料

从 HuggingFace 加载新闻分类数据集 `valurank/News_Articles_Categorization`，取前 **10 条**作为演示语料。

每条样本包含 `Text`（正文）和 `Category`（类别）。先查看文本长度，了解后续切分规模。

In [11]:
from datasets import load_dataset

ds = load_dataset("valurank/News_Articles_Categorization")
my_ds = ds["train"].select(range(10))
my_ds

Dataset({
    features: ['Text', 'Category'],
    num_rows: 10
})

In [15]:
for d in my_ds['Text']:
    print(len(d))
    print(d[:100])

721
Elon Musk, Amber Heard Something's Fishy On Wrapped-Up Sushi Last we heard, Elon Musk and Amber Hear
4749
Scientists are developing more than 100 coronavirus vaccines using a range of techniques, some of wh
721
Jared Fogle Shut Down By Judge In Bid for Early Release 1/22/2018 Jared Fogle got no love from the j
5565
The agency had come under fire from members of Congress and other groups for allowing dozens of wild
13988
Credit...Jim Wilson/The New York TimesJune 30, 2018WASHINGTON On the final day of the Supreme Court
14264
Before Coming Out, a Hard Time Growing UpVideoMichael Sam, a defensive end at Missouri who will ente
7950
Credit...Laurent Cipriani/Associated PressNov. 20, 2018BRUSSELS Gathered at a glitzy Dubai resort th
5138
Fortnites parent company, Epic Games, had broken its contract with Apple, a federal judge found. The
771
Lil Pump Attention Record Companies ... $15 Mil or Take a Hike 1/27/2018 TMZ.com Lil Pump is super h
10305
The InterpreterCredit...Jean-Paul Pelissier/ReutersMarch 6, 2017BERLIN An idea, once unthinkable, is

---

## Part 3 — 文档切分（Chunking）

使用 `RecursiveCharacterTextSplitter` 将长文切分为适合检索的片段：

| 参数 | 值 | 说明 |
|------|-----|------|
| `chunk_size` | 350 tokens | 按 tiktoken 计数，非字符数 |
| `chunk_overlap` | 70 tokens | 相邻 chunk 重叠，减少边界截断 |
| `separators` | 段落 → 句号 | 优先在语义边界切分 |

每个 chunk 封装为 LangChain `Document`，metadata 记录 `doc_index` / `chunk_index`，便于追溯来源。

In [16]:
from langchain_text_splitters import RecursiveCharacterTextSplitter
import tiktoken
from langchain_core.documents import Document

tokenizer = tiktoken.get_encoding("cl100k_base")

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=350,
    chunk_overlap=70,
    separators=["\n\n", "\n", ".", "!", "?"],
    length_function=lambda x: len(tokenizer.encode(x))
)

all_chunks2 = []
for i, t in enumerate(my_ds['Text']):
    chunks = text_splitter.split_text(t)
    total_chunks = len(chunks)
    for j, chunk_text in enumerate(chunks):
        all_chunks2.append(Document(
            page_content=chunk_text,
            metadata={"source":i, "doc_index": i, "chunk_index": j, "total_chunks": total_chunks}
        ))
        print(chunk_text)
        print("="*60)
print(f"Total chunks: {len(all_chunks2)}")

Elon Musk, Amber Heard Something's Fishy On Wrapped-Up Sushi Last we heard, Elon Musk and Amber Heard were "not back together" even though they kiss goodbye and dance real close ... sorry, we're not buying that now. Amber and Elon went on a sushi date Monday in WeHo, and looked like the full-blown hand-holding couple that's definitely on again. But that's only because that's exactly what they are -- no matter how many times they try to say they're not reunited. We broke the story ... Elon and Amber started hanging out again this past fall ... after announcing their split in the summer. Since then, they've smooched and gone dancing together. If it looks like a reunited duck, walks like a reunited duck ... TMZ.com
============================================================
Scientists are developing more than 100 coronavirus vaccines using a range of techniques, some of which are well-established and some of which have never been approved for medical use before. Most of these vaccines target the so-called spike proteins that cover the virus and help it invade human cells. The immune system can develop antibodies that latch onto spike proteins and stop the virus. A successful vaccine for the SARS-CoV-2 coronavirus would teach peoples immune systems to make antibodies against the virus without causing disease. Whole-Virus Vaccines Vaccines that modify the entire coronavirus to provoke an immune response. Inactivated and Live Attenuated Vaccines Most vaccines in use today incorporate an inactivated or weakened form of a virus that is not able to cause disease. When immune cells encounter them, they make antibodies. Making these vaccines means growing viruses and lots of them. Influenza vaccines are typically grown in chicken eggs, and other vaccines are grown in tanks full of floating cells. These procedures can take months to produce a batch of new vaccines. EXAMPLES: Conventional vaccines for influenza, chickenpox, measles, mumps and rubella all fall into this category. COMPANIES DEVELOPING SARS-COV-2 VACCINES: Sinovac and others. Genetic Vaccines Vaccines that use part of the coronaviruss genetic code. DNA Vaccines A number of experimental coronavirus vaccines dont deliver whole viruses. Instead, they deliver genetic instructions for building a viral protein. The protein can then stimulate the immune system to make antibodies and help mount other defenses against the coronavirus. One of these genetic approaches is known as a DNA vaccine. A circle of engineered DNA is delivered into cells
============================================================
. DNA Vaccines A number of experimental coronavirus vaccines dont deliver whole viruses. Instead, they deliver genetic instructions for building a viral protein. The protein can then stimulate the immune system to make antibodies and help mount other defenses against the coronavirus. One of these genetic approaches is known as a DNA vaccine. A circle of engineered DNA is delivered into cells. The cells read the viral gene, make a copy in a molecule called messenger RNA, and then use the mRNA to assemble viral proteins. The immune system detects the proteins and mounts defenses. Prototype DNA vaccines based on the spike protein protected monkeys from the coronavirus. EXAMPLES: DNA vaccines have been approved for veterinary cases such as canine melanoma and West Nile virus in horses. There are no approved DNA vaccines for use in humans, but researchers are running trials to see if they might be effective for diseases such as Zika and the flu. COMPANIES: Inovio and others. RNA Vaccines Some researchers want to skip DNA and instead deliver messenger RNA into cells. The cells read the mRNA and make spike proteins that provoke an immune response. The biotech company Moderna recently completed a small safety trial with eight volunteers that showed promising early results against the coronavirus. Both RNA and DNA vaccines can be produced more quickly than traditional methods. EXAMPLES: There are no approved RNA vaccines, but they are in clinical trials for MERS and other diseases. COMPANIES: Moderna, Pfizer and BioNTech, CureVac and others. Viral Vector Vaccines Vaccines that use a virus to deliver coronavirus genes into cells. Vaccines Using Adenovirus or Other Viruses Viruses are very good at getting into cells
============================================================
. COMPANIES: Moderna, Pfizer and BioNTech, CureVac and others. Viral Vector Vaccines Vaccines that use a virus to deliver coronavirus genes into cells. Vaccines Using Adenovirus or Other Viruses Viruses are very good at getting into cells. Since the 1990s, researchers have been investigating how to use them to deliver genes into cells to immunize people against diseases. To create a coronavirus vaccine, several teams have added the spike protein gene to a virus called an adenovirus. The adenovirus slips into cells and unloads the gene. Because the adenovirus is missing one of its own genes, it cannot replicate and is therefore safe. EXAMPLES: Several virus vector vaccines are used to vaccinate animals against rabies and distemper. Johnson & Johnson has developed H.I.V. and Ebola vaccines using an adenovirus. Both have proven safe in humans and are now in efficacy trials. COMPANIES: Johnson & Johnson, CanSino, University of Oxford and others. Protein-Based Vaccines Vaccines that use a coronavirus protein or a protein fragment. Virus-Like Particle Vaccines Some vaccines are particles that contain pieces of viral proteins. They cant cause disease because they are not actual viruses, but they can still show the immune system what coronavirus proteins look like. EXAMPLES: The vaccine for HPV falls into this category. COMPANIES: Medicago, Doherty Institute and others. Recombinant Vaccines Yeast or other cells can be engineered to carry a viruss gene and spew out viral proteins, which are then harvested and put into a vaccine. A coronavirus vaccine of this design would contain whole spike proteins or small pieces of the protein
============================================================
. COMPANIES: Medicago, Doherty Institute and others. Recombinant Vaccines Yeast or other cells can be engineered to carry a viruss gene and spew out viral proteins, which are then harvested and put into a vaccine. A coronavirus vaccine of this design would contain whole spike proteins or small pieces of the protein. EXAMPLES: This category includes some vaccines for shingles and hepatitis B. COMPANIES: Novavax and others. Sources: World Health Organization, National Institute of Allergy and Infectious Diseases, National Center for Biotechnology Information, NEJM
============================================================
Jared Fogle Shut Down By Judge In Bid for Early Release 1/22/2018 Jared Fogle got no love from the judge who sentenced him to 15 years in prison ... ruling his legal arguments were BS. Fogle had filed legal docs he prepared himself in the prison library, claiming Judge Tanya Pratt had no jurisdiction to even hear the criminal case because the sex crime charges required proof he traveled from one state to another to engage in sex acts with minors ... and he says everything was done in 1 state. Judge Pratt begged to differ, repeatedly calling Fogle's argument "frivolous," saying federal law specifically covers his crimes. The judge invited him to appeal to a higher court, but made it clear ... that dog don't hunt.
============================================================
The agency had come under fire from members of Congress and other groups for allowing dozens of wildly inaccurate tests to proliferate without oversight.Credit...David J. Phillip/Associated PressPublished May 4, 2020Updated May 7, 2020The Food and Drug Administration announced on Monday that companies selling coronavirus antibody tests must submit data proving accuracy within the next 10 days or face removal from the market.The antibody tests are an effort to detect whether a person had been infected with the coronavirus, but results have been widely varied. Since mid-March, the agency has permitted dozens of manufacturers to sell the tests without providing evidence that they are accurate.The F.D.A.s action follows a report by more than 50 scientists, which found that only three out of 14 antibody tests gave consistently reliable results, and even the best had flaws. An evaluation by the National Institutes of Health, working with other federal health agencies, has also found a concerning number of commercial tests that are performing poorly, the F.D.A. said.The agency has also been under fire from several members of Congress, with numerous lawmakers raising questions about the validity of some of the tests.So far, little is known about whether those who became ill will develop immunity and, if so, for how long, and that leaves the value of antibody tests still uncertain. Around the globe, government and health officials have hoped that antibody tests would be a critical tool to help determine when it would be safe to lift stay-at-home restrictions and reopen businesses. The tests might also be used to identify potential donors of convalescent plasma, an approach in which blood plasma containing antibodies from a recovered individual is used to treat a Covid-19 patient, the F.D.A. said
============================================================
. The tests might also be used to identify potential donors of convalescent plasma, an approach in which blood plasma containing antibodies from a recovered individual is used to treat a Covid-19 patient, the F.D.A. said.The highly infectious disease has now killed nearly 70,000 people and sickened more than 1.1 million in the United States alone.While 12 companies have been given F.D.A. clearance to sell the antibody tests, many other products do not have agency authorization. The result has been a confusing landscape in which tests by established companies such as Abbott Laboratories, Cellex and most recently, Roche Diagnostics, are competing with unapproved tests made by unknown companies and sold by U.S. distributors with spotty track records. The F.D.A. has blocked imports of some antibody tests at the U.S. border, and has ordered some distributors to revise claims about what individuals can learn from them, or halt sales.House Democrats Raja Krishnamoorthi, of Illinois, and Rosa DeLauro, of Connecticut, have both criticized the agency for its handling of the matter as has Representative Lloyd Doggett, Democrat of Texas.The administrations original serology testing policy, which allowed tests on the market with no F.D.A. review, felt like an overreaction to the criticism they faced for their slow rollout of molecular tests, Mr. Krishnamoorthi said. But F.D.A. went too far, completely abrogating regulatory responsibility.Overseeing development of coronavirus tests has been rocky from the start, with President Trump and others urging the agency to relax rules for commercial tests
============================================================
. Krishnamoorthi said. But F.D.A. went too far, completely abrogating regulatory responsibility.Overseeing development of coronavirus tests has been rocky from the start, with President Trump and others urging the agency to relax rules for commercial tests. Beginning in late February, the agency came under fire for taking too long to allow private companies to get diagnostic tests for the coronavirus onto the market. Now, the F.D.A. faces additional scrutiny for permitting manufacturers to distribute the antibody tests too quickly without proof of efficacy.Every step this agency has taken in response to Covid-19 has been a balance of risk and benefits, said Dr. Stephen Hahn, the F.D.A. commissioner, in a telephone call with reporters on Monday.In a statement on Monday, Dr. Anand Shah, the F.D.A. deputy commissioner for medical and scientific affairs, and Dr. Jeffrey Shuren, director of the Center for Devices and Radiological Health, defended the agencys initial policy, saying the tests were never intended to be used as the sole basis for determining whether anyone had been infected.We unfortunately see unscrupulous actors marketing fraudulent test kits and using the pandemic as an opportunity to take advantage of Americans anxiety, they said in the statement. Some test developers have falsely claimed their serology tests are F.D.A. approved or authorized. Others have falsely claimed that their tests can diagnose Covid-19 or that they are for at-home testing.Dr. Shah and Dr. Shuren also pointed to the N.I.H. evaluation that showed a number of tests producing faulty results. The F.D.A. declined to provide details on the number of tests that were studied, or how many did not work. They also said that the F
============================================================
.Dr. Shah and Dr. Shuren also pointed to the N.I.H. evaluation that showed a number of tests producing faulty results. The F.D.A. declined to provide details on the number of tests that were studied, or how many did not work. They also said that the F.D.A. is reviewing more than 200 antibody tests to determine whether they work well enough to get the agencys go-ahead.Scott Becker, the chief executive of the Association of Public Health Laboratories, was pleased by the F.D.A.s announcement, which he said would improve the quality of antibody tests. He also said the crackdown comes six weeks too late.The Food and Drug Administration made the right decision by walking back its policy on serology testing for Covid-19, Mr. Becker said. Weve long been concerned that allowing tests on the market that have not been approved and authorized for use is a recipe for disaster.In addition, as states and cities look for ways to reopen businesses, Dr. Hahn said on Monday: Whether a test should be a ticket for someone to go back to work as the sole item, my opinion on that would be no, because there are a lot of unanswered questions.
============================================================
Credit...Jim Wilson/The New York TimesJune 30, 2018WASHINGTON On the final day of the Supreme Court term last week, Justice Elena Kagan sounded an alarm.The courts five conservative members, citing the First Amendment, had just dealt public unions a devastating blow. The day before, the same majority had used the First Amendment to reject a California law requiring religiously oriented crisis pregnancy centers to provide women with information about abortion.Conservatives, said Justice Kagan, who is part of the courts four-member liberal wing, were weaponizing the First Amendment.The two decisions were the latest in a stunning run of victories for a conservative agenda that has increasingly been built on the foundation of free speech. Conservative groups, borrowing and building on arguments developed by liberals, have used the First Amendment to justify unlimited campaign spending, discrimination against gay couples and attacks on the regulation of tobacco, pharmaceuticals and guns.The right, which had for years been hostile to and very nervous about a strong First Amendment, has rediscovered it, said Burt Neuborne, a law professor at New York University.The Citizens United campaign finance case, for instance, was decided on free-speech grounds, with the five-justice conservative majority ruling that the First Amendment protects unlimited campaign spending by corporations. The government, the majority said, has no business regulating political speech.The dissenters responded that the First Amendment did not require allowing corporate money to flood the political marketplace and corrupt democracy.The libertarian position has become dominant on the right on First Amendment issues, said Ilya Shapiro, a lawyer with the Cato Institute. It simply means that we should be skeptical of government attempts to regulate speech. That used to be an uncontroversial and nonideological point
============================================================
.The libertarian position has become dominant on the right on First Amendment issues, said Ilya Shapiro, a lawyer with the Cato Institute. It simply means that we should be skeptical of government attempts to regulate speech. That used to be an uncontroversial and nonideological point. Whats now being called the libertarian position on speech was in the 1960s the liberal position on speech.And an increasingly conservative judiciary has been more than a little receptive to this argument. A new analysis prepared for The New York Times found that the Supreme Court under Chief Justice John G. Roberts Jr. has been far more likely to embrace free-speech arguments concerning conservative speech than liberal speech. That is a sharp break from earlier eras.As a result, liberals who once championed expansive First Amendment rights are now uneasy about them.The left was once not just on board but leading in supporting the broadest First Amendment protections, said Floyd Abrams, a prominent First Amendment lawyer and a supporter of broad free-speech rights. Now the progressive community is at least skeptical and sometimes distraught at the level of First Amendment protection which is being afforded in cases brought by litigants on the right.Many on the left have traded an absolutist commitment to free speech for one sensitive to the harms it can inflict.Take pornography and street protests. Liberals were once largely united in fighting to protect sexually explicit materials from government censorship. Now many on the left see pornography as an assault on womens rights.In 1977, many liberals supported the right of the American Nazi Party to march among Holocaust survivors in Skokie, Ill. Far fewer supported the free-speech rights of the white nationalists who marched last year in Charlottesville, Va
============================================================
. Now many on the left see pornography as an assault on womens rights.In 1977, many liberals supported the right of the American Nazi Party to march among Holocaust survivors in Skokie, Ill. Far fewer supported the free-speech rights of the white nationalists who marched last year in Charlottesville, Va.There was a certain navet in how liberals used to approach free speech, said Frederick Schauer, a law professor at the University of Virginia.Because so many free-speech claims of the 1950s and 1960s involved anti-obscenity claims, or civil rights and anti-Vietnam War protests, it was easy for the left to sympathize with the speakers or believe that speech in general was harmless, he said. But the claim that speech was harmless or causally inert was never true, even if it has taken recent events to convince the left of that. The question, then, is why the left ever believed otherwise.Some liberals now say that free speech disproportionately protects the powerful and the status quo.When I was younger, I had more of the standard liberal view of civil liberties, said Louis Michael Seidman, a law professor at Georgetown. And Ive gradually changed my mind about it. What I have come to see is that its a mistake to think of free speech as an effective means to accomplish a more just society.To the contrary, free speech reinforces and amplifies injustice, Catharine A. MacKinnon, a law professor at the University of Michigan, wrote in The Free Speech Century, a collection of essays to be published this year.Once a defense of the powerless, the First Amendment over the last hundred years has mainly become a weapon of the powerful, she wrote
============================================================

In [ ]:
for c in all_chunks2:
    print(c.metadata['doc_index'], c.metadata['chunk_index'], c.page_content)
    print('\n========\n')

0 0 Elon Musk, Amber Heard Something's Fishy On Wrapped-Up Sushi Last we heard, Elon Musk and Amber Heard were "not back together" even though they kiss goodbye and dance real close ... sorry, we're not buying that now. Amber and Elon went on a sushi date Monday in WeHo, and looked like the full-blown hand-holding couple that's definitely on again. But that's only because that's exactly what they are -- no matter how many times they try to say they're not reunited. We broke the story ... Elon and Amber started hanging out again this past fall ... after announcing their split in the summer. Since then, they've smooched and gone dancing together. If it looks like a reunited duck, walks like a reunited duck ... TMZ.com

========

1 0 Scientists are developing more than 100 coronavirus vaccines using a range of techniques, some of which are well-established and some of which have never been approved for medical use before. Most of these vaccines target the so-called spike proteins that cover the virus and help it invade human cells. The immune system can develop antibodies that latch onto spike proteins and stop the virus. A successful vaccine for the SARS-CoV-2 coronavirus would teach peoples immune systems to make antibodies against the virus without causing disease. Whole-Virus Vaccines Vaccines that modify the entire coronavirus to provoke an immune response. Inactivated and Live Attenuated Vaccines Most vaccines in use today incorporate an inactivated or weakened form of a virus that is not able to cause disease. When immune cells encounter them, they make antibodies. Making these vaccines means growing viruses and lots of them. Influenza vaccines are typically grown in chicken eggs, and other vaccines are grown in tanks full of floating cells. These procedures can take months to produce a batch of new vaccines. EXAMPLES: Conventional vaccines for influenza, chickenpox, measles, mumps and rubella all fall into this category. COMPANIES DEVELOPING SARS-COV-2 VACCINES: Sinovac and others. Genetic Vaccines Vaccines that use part of the coronaviruss genetic code. DNA Vaccines A number of experimental coronavirus vaccines dont deliver whole viruses. Instead, they deliver genetic instructions for building a viral protein. The protein can then stimulate the immune system to make antibodies and help mount other defenses against the coronavirus. One of these genetic approaches is known as a DNA vaccine. A circle of engineered DNA is delivered into cells

========

1 1 . DNA Vaccines A number of experimental coronavirus vaccines dont deliver whole viruses. Instead, they deliver genetic instructions for building a viral protein. The protein can then stimulate the immune system to make antibodies and help mount other defenses against the coronavirus. One of these genetic approaches is known as a DNA vaccine. A circle of engineered DNA is delivered into cells. The cells read the viral gene, make a copy in a molecule called messenger RNA, and then use the mRNA to assemble viral proteins. The immune system detects the proteins and mounts defenses. Prototype DNA vaccines based on the spike protein protected monkeys from the coronavirus. EXAMPLES: DNA vaccines have been approved for veterinary cases such as canine melanoma and West Nile virus in horses. There are no approved DNA vaccines for use in humans, but researchers are running trials to see if they might be effective for diseases such as Zika and the flu. COMPANIES: Inovio and others. RNA Vaccines Some researchers want to skip DNA and instead deliver messenger RNA into cells. The cells read the mRNA and make spike proteins that provoke an immune response. The biotech company Moderna recently completed a small safety trial with eight volunteers that showed promising early results against the coronavirus. Both RNA and DNA vaccines can be produced more quickly than traditional methods. EXAMPLES: There are no approved RNA vaccines, but they are in clinical trials for MERS and other diseases. COMPANIES: Moderna, Pfizer and BioNTech, CureVac and others. Viral Vector Vaccines Vaccines that use a virus to deliver coronavirus genes into cells. Vaccines Using Adenovirus or Other Viruses Viruses are very good at getting into cells

========

1 2 . COMPANIES: Moderna, Pfizer and BioNTech, CureVac and others. Viral Vector Vaccines Vaccines that use a virus to deliver coronavirus genes into cells. Vaccines Using Adenovirus or Other Viruses Viruses are very good at getting into cells. Since the 1990s, researchers have been investigating how to use them to deliver genes into cells to immunize people against diseases. To create a coronavirus vaccine, several teams have added the spike protein gene to a virus called an adenovirus. The adenovirus slips into cells and unloads the gene. Because the adenovirus is missing one of its own genes, it cannot replicate and is therefore safe. EXAMPLES: Several virus vector vaccines are used to vaccinate animals against rabies and distemper. Johnson & Johnson has developed H.I.V. and Ebola vaccines using an adenovirus. Both have proven safe in humans and are now in efficacy trials. COMPANIES: Johnson & Johnson, CanSino, University of Oxford and others. Protein-Based Vaccines Vaccines that use a coronavirus protein or a protein fragment. Virus-Like Particle Vaccines Some vaccines are particles that contain pieces of viral proteins. They cant cause disease because they are not actual viruses, but they can still show the immune system what coronavirus proteins look like. EXAMPLES: The vaccine for HPV falls into this category. COMPANIES: Medicago, Doherty Institute and others. Recombinant Vaccines Yeast or other cells can be engineered to carry a viruss gene and spew out viral proteins, which are then harvested and put into a vaccine. A coronavirus vaccine of this design would contain whole spike proteins or small pieces of the protein

========

1 3 . COMPANIES: Medicago, Doherty Institute and others. Recombinant Vaccines Yeast or other cells can be engineered to carry a viruss gene and spew out viral proteins, which are then harvested and put into a vaccine. A coronavirus vaccine of this design would contain whole spike proteins or small pieces of the protein. EXAMPLES: This category includes some vaccines for shingles and hepatitis B. COMPANIES: Novavax and others. Sources: World Health Organization, National Institute of Allergy and Infectious Diseases, National Center for Biotechnology Information, NEJM

========

2 0 Jared Fogle Shut Down By Judge In Bid for Early Release 1/22/2018 Jared Fogle got no love from the judge who sentenced him to 15 years in prison ... ruling his legal arguments were BS. Fogle had filed legal docs he prepared himself in the prison library, claiming Judge Tanya Pratt had no jurisdiction to even hear the criminal case because the sex crime charges required proof he traveled from one state to another to engage in sex acts with minors ... and he says everything was done in 1 state. Judge Pratt begged to differ, repeatedly calling Fogle's argument "frivolous," saying federal law specifically covers his crimes. The judge invited him to appeal to a higher court, but made it clear ... that dog don't hunt.

========

3 0 The agency had come under fire from members of Congress and other groups for allowing dozens of wildly inaccurate tests to proliferate without oversight.Credit...David J. Phillip/Associated PressPublished May 4, 2020Updated May 7, 2020The Food and Drug Administration announced on Monday that companies selling coronavirus antibody tests must submit data proving accuracy within the next 10 days or face removal from the market.The antibody tests are an effort to detect whether a person had been infected with the coronavirus, but results have been widely varied. Since mid-March, the agency has permitted dozens of manufacturers to sell the tests without providing evidence that they are accurate.The F.D.A.s action follows a report by more than 50 scientists, which found that only three out of 14 antibody tests gave consistently reliable results, and even the best had flaws. An evaluation by the National Institutes of Health, working with other federal health agencies, has also found a concerning number of commercial tests that are performing poorly, the F.D.A. said.The agency has also been under fire from several members of Congress, with numerous lawmakers raising questions about the validity of some of the tests.So far, little is known about whether those who became ill will develop immunity and, if so, for how long, and that leaves the value of antibody tests still uncertain. Around the globe, government and health officials have hoped that antibody tests would be a critical tool to help determine when it would be safe to lift stay-at-home restrictions and reopen businesses. The tests might also be used to identify potential donors of convalescent plasma, an approach in which blood plasma containing antibodies from a recovered individual is used to treat a Covid-19 patient, the F.D.A. said

========

3 1 . The tests might also be used to identify potential donors of convalescent plasma, an approach in which blood plasma containing antibodies from a recovered individual is used to treat a Covid-19 patient, the F.D.A. said.The highly infectious disease has now killed nearly 70,000 people and sickened more than 1.1 million in the United States alone.While 12 companies have been given F.D.A. clearance to sell the antibody tests, many other products do not have agency authorization. The result has been a confusing landscape in which tests by established companies such as Abbott Laboratories, Cellex and most recently, Roche Diagnostics, are competing with unapproved tests made by unknown companies and sold by U.S. distributors with spotty track records. The F.D.A. has blocked imports of some antibody tests at the U.S. border, and has ordered some distributors to revise claims about what individuals can learn from them, or halt sales.House Democrats Raja Krishnamoorthi, of Illinois, and Rosa DeLauro, of Connecticut, have both criticized the agency for its handling of the matter as has Representative Lloyd Doggett, Democrat of Texas.The administrations original serology testing policy, which allowed tests on the market with no F.D.A. review, felt like an overreaction to the criticism they faced for their slow rollout of molecular tests, Mr. Krishnamoorthi said. But F.D.A. went too far, completely abrogating regulatory responsibility.Overseeing development of coronavirus tests has been rocky from the start, with President Trump and others urging the agency to relax rules for commercial tests

========

3 2 . Krishnamoorthi said. But F.D.A. went too far, completely abrogating regulatory responsibility.Overseeing development of coronavirus tests has been rocky from the start, with President Trump and others urging the agency to relax rules for commercial tests. Beginning in late February, the agency came under fire for taking too long to allow private companies to get diagnostic tests for the coronavirus onto the market. Now, the F.D.A. faces additional scrutiny for permitting manufacturers to distribute the antibody tests too quickly without proof of efficacy.Every step this agency has taken in response to Covid-19 has been a balance of risk and benefits, said Dr. Stephen Hahn, the F.D.A. commissioner, in a telephone call with reporters on Monday.In a statement on Monday, Dr. Anand Shah, the F.D.A. deputy commissioner for medical and scientific affairs, and Dr. Jeffrey Shuren, director of the Center for Devices and Radiological Health, defended the agencys initial policy, saying the tests were never intended to be used as the sole basis for determining whether anyone had been infected.We unfortunately see unscrupulous actors marketing fraudulent test kits and using the pandemic as an opportunity to take advantage of Americans anxiety, they said in the statement. Some test developers have falsely claimed their serology tests are F.D.A. approved or authorized. Others have falsely claimed that their tests can diagnose Covid-19 or that they are for at-home testing.Dr. Shah and Dr. Shuren also pointed to the N.I.H. evaluation that showed a number of tests producing faulty results. The F.D.A. declined to provide details on the number of tests that were studied, or how many did not work. They also said that the F

========

3 3 .Dr. Shah and Dr. Shuren also pointed to the N.I.H. evaluation that showed a number of tests producing faulty results. The F.D.A. declined to provide details on the number of tests that were studied, or how many did not work. They also said that the F.D.A. is reviewing more than 200 antibody tests to determine whether they work well enough to get the agencys go-ahead.Scott Becker, the chief executive of the Association of Public Health Laboratories, was pleased by the F.D.A.s announcement, which he said would improve the quality of antibody tests. He also said the crackdown comes six weeks too late.The Food and Drug Administration made the right decision by walking back its policy on serology testing for Covid-19, Mr. Becker said. Weve long been concerned that allowing tests on the market that have not been approved and authorized for use is a recipe for disaster.In addition, as states and cities look for ways to reopen businesses, Dr. Hahn said on Monday: Whether a test should be a ticket for someone to go back to work as the sole item, my opinion on that would be no, because there are a lot of unanswered questions.

========

4 0 Credit...Jim Wilson/The New York TimesJune 30, 2018WASHINGTON On the final day of the Supreme Court term last week, Justice Elena Kagan sounded an alarm.The courts five conservative members, citing the First Amendment, had just dealt public unions a devastating blow. The day before, the same majority had used the First Amendment to reject a California law requiring religiously oriented crisis pregnancy centers to provide women with information about abortion.Conservatives, said Justice Kagan, who is part of the courts four-member liberal wing, were weaponizing the First Amendment.The two decisions were the latest in a stunning run of victories for a conservative agenda that has increasingly been built on the foundation of free speech. Conservative groups, borrowing and building on arguments developed by liberals, have used the First Amendment to justify unlimited campaign spending, discrimination against gay couples and attacks on the regulation of tobacco, pharmaceuticals and guns.The right, which had for years been hostile to and very nervous about a strong First Amendment, has rediscovered it, said Burt Neuborne, a law professor at New York University.The Citizens United campaign finance case, for instance, was decided on free-speech grounds, with the five-justice conservative majority ruling that the First Amendment protects unlimited campaign spending by corporations. The government, the majority said, has no business regulating political speech.The dissenters responded that the First Amendment did not require allowing corporate money to flood the political marketplace and corrupt democracy.The libertarian position has become dominant on the right on First Amendment issues, said Ilya Shapiro, a lawyer with the Cato Institute. It simply means that we should be skeptical of government attempts to regulate speech. That used to be an uncontroversial and nonideological point

========

4 1 .The libertarian position has become dominant on the right on First Amendment issues, said Ilya Shapiro, a lawyer with the Cato Institute. It simply means that we should be skeptical of government attempts to regulate speech. That used to be an uncontroversial and nonideological point. Whats now being called the libertarian position on speech was in the 1960s the liberal position on speech.And an increasingly conservative judiciary has been more than a little receptive to this argument. A new analysis prepared for The New York Times found that the Supreme Court under Chief Justice John G. Roberts Jr. has been far more likely to embrace free-speech arguments concerning conservative speech than liberal speech. That is a sharp break from earlier eras.As a result, liberals who once championed expansive First Amendment rights are now uneasy about them.The left was once not just on board but leading in supporting the broadest First Amendment protections, said Floyd Abrams, a prominent First Amendment lawyer and a supporter of broad free-speech rights. Now the progressive community is at least skeptical and sometimes distraught at the level of First Amendment protection which is being afforded in cases brought by litigants on the right.Many on the left have traded an absolutist commitment to free speech for one sensitive to the harms it can inflict.Take pornography and street protests. Liberals were once largely united in fighting to protect sexually explicit materials from government censorship. Now many on the left see pornography as an assault on womens rights.In 1977, many liberals supported the right of the American Nazi Party to march among Holocaust survivors in Skokie, Ill. Far fewer supported the free-speech rights of the white nationalists who marched last year in Charlottesville, Va

========

4 2 . Now many on the left see pornography as an assault on womens rights.In 1977, many liberals supported the right of the American Nazi Party to march among Holocaust survivors in Skokie, Ill. Far fewer supported the free-speech rights of the white nationalists who marched last year in Charlottesville, Va.There was a certain navet in how liberals used to approach free speech, said Frederick Schauer, a law professor at the University of Virginia.Because so many free-speech claims of the 1950s and 1960s involved anti-obscenity claims, or civil rights and anti-Vietnam War protests, it was easy for the left to sympathize with the speakers or believe that speech in general was harmless, he said. But the claim that speech was harmless or causally inert was never true, even if it has taken recent events to convince the left of that. The question, then, is why the left ever believed otherwise.Some liberals now say that free speech disproportionately protects the powerful and the status quo.When I was younger, I had more of the standard liberal view of civil liberties, said Louis Michael Seidman, a law professor at Georgetown. And Ive gradually changed my mind about it. What I have come to see is that its a mistake to think of free speech as an effective means to accomplish a more just society.To the contrary, free speech reinforces and amplifies injustice, Catharine A. MacKinnon, a law professor at the University of Michigan, wrote in The Free Speech Century, a collection of essays to be published this year.Once a defense of the powerless, the First Amendment over the last hundred years has mainly become a weapon of the powerful, she wrote

========


---

## Part 4 — Ragas 官方测试集生成

使用 Ragas `TestsetGenerator` 从 chunk 列表**自动合成**评测样本。

**内部流程（简化）：**

1. 对 chunk 做摘要、过滤、主题/实体抽取
2. 构建 chunk 间相似度图
3. 生成 Persona → 生成查询场景 → 合成 QA 对

本例仅启用 `SingleHopSpecificQuerySynthesizer`（单跳、具体问题），生成 5 条样本。每条包含：

- `user_input` — 用户问题
- `reference` — 标准答案
- `reference_contexts` — 出题依据的原文片段

In [18]:
from ragas.testset import TestsetGenerator
from ragas.testset.persona import Persona
from ragas.testset.synthesizers import default_query_distribution, SingleHopSpecificQuerySynthesizer, MultiHopAbstractQuerySynthesizer, MultiHopSpecificQuerySynthesizer

query_distribution = [
    (SingleHopSpecificQuerySynthesizer(), 1),
    # (MultiHopSpecificQuerySynthesizer(), 0.3),
    # (MultiHopAbstractQuerySynthesizer(), 0.1),
]

generator = TestsetGenerator(
    llm=generator_llm,
    embedding_model=generator_embeddings,
)


testset = generator.generate_with_langchain_docs(
    all_chunks2,
    testset_size=5,
    query_distribution=query_distribution,
)
testset

Applying SummaryExtractor:   0%|          | 0/49 [00:00<?, ?it/s]

Applying CustomNodeFilter:   0%|          | 0/49 [00:00<?, ?it/s]

Applying [EmbeddingExtractor, ThemesExtractor, NERExtractor]:   0%|          | 0/147 [00:00<?, ?it/s]

Applying [CosineSimilarityBuilder, OverlapScoreBuilder]:   0%|          | 0/2 [00:00<?, ?it/s]

Generating personas:   0%|          | 0/3 [00:00<?, ?it/s]

Generating Scenarios:   0%|          | 0/1 [00:00<?, ?it/s]

Generating Samples:   0%|          | 0/5 [00:00<?, ?it/s]

Testset(samples=[TestsetSample(eval_sample=SingleTurnSample(user_input='What recent activities have Elon Musk and Amber Heard engaged in while in WeHo?', retrieved_contexts=None, reference_contexts=['Elon Musk, Amber Heard Something\'s Fishy On Wrapped-Up Sushi Last we heard, Elon Musk and Amber Heard were "not back together" even though they kiss goodbye and dance real close ... sorry, we\'re not buying that now. Amber and Elon went on a sushi date Monday in WeHo, and looked like the full-blown hand-holding couple that\'s definitely on again. But that\'s only because that\'s exactly what they are -- no matter how many times they try to say they\'re not reunited. We broke the story ... Elon and Amber started hanging out again this past fall ... after announcing their split in the summer. Since then, they\'ve smooched and gone dancing together. If it looks like a reunited duck, walks like a reunited duck ... TMZ.com'], response=None, multi_responses=None, reference='Elon Musk and Amber Heard were spotted on a sushi date in WeHo, where they appeared to be a full-blown hand-holding couple, suggesting they are indeed back together despite claims that they are not.', rubrics=None), synthesizer_name='single_hop_specifc_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='How are scientists approaching the development of coronavirus vaccines?', retrieved_contexts=None, reference_contexts=['Scientists are developing more than 100 coronavirus vaccines using a range of techniques, some of which are well-established and some of which have never been approved for medical use before. Most of these vaccines target the so-called spike proteins that cover the virus and help it invade human cells. The immune system can develop antibodies that latch onto spike proteins and stop the virus. A successful vaccine for the SARS-CoV-2 coronavirus would teach peoples immune systems to make antibodies against the virus without causing disease. Whole-Virus Vaccines Vaccines that modify the entire coronavirus to provoke an immune response. Inactivated and Live Attenuated Vaccines Most vaccines in use today incorporate an inactivated or weakened form of a virus that is not able to cause disease. When immune cells encounter them, they make antibodies. Making these vaccines means growing viruses and lots of them. Influenza vaccines are typically grown in chicken eggs, and other vaccines are grown in tanks full of floating cells. These procedures can take months to produce a batch of new vaccines. EXAMPLES: Conventional vaccines for influenza, chickenpox, measles, mumps and rubella all fall into this category. COMPANIES DEVELOPING SARS-COV-2 VACCINES: Sinovac and others. Genetic Vaccines Vaccines that use part of the coronaviruss genetic code. DNA Vaccines A number of experimental coronavirus vaccines dont deliver whole viruses. Instead, they deliver genetic instructions for building a viral protein. The protein can then stimulate the immune system to make antibodies and help mount other defenses against the coronavirus. One of these genetic approaches is known as a DNA vaccine. A circle of engineered DNA is delivered into cells'], response=None, multi_responses=None, reference="Scientists are developing more than 100 coronavirus vaccines using a range of techniques, some of which are well-established and some of which have never been approved for medical use before. Most of these vaccines target the spike proteins that cover the virus and help it invade human cells, allowing the immune system to develop antibodies that latch onto these proteins and stop the virus. A successful vaccine for the SARS-CoV-2 coronavirus would teach people's immune systems to make antibodies against the virus without causing disease.", rubrics=None), synthesizer_name='single_hop_specifc_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='How did DNA vaccines protect monkeys from the coronavirus?', retrieved_contexts=None, reference_contexts=['. DNA Vaccines A number of experimental coronavirus vaccines dont deliver whole viruses. Instead, they deliver genetic instructions for building a viral protein. The protein can then stimulate the immune system to make antibodies and help mount other defenses against the coronavirus. One of these genetic approaches is known as a DNA vaccine. A circle of engineered DNA is delivered into cells. The cells read the viral gene, make a copy in a molecule called messenger RNA, and then use the mRNA to assemble viral proteins. The immune system detects the proteins and mounts defenses. Prototype DNA vaccines based on the spike protein protected monkeys from the coronavirus. EXAMPLES: DNA vaccines have been approved for veterinary cases such as canine melanoma and West Nile virus in horses. There are no approved DNA vaccines for use in humans, but researchers are running trials to see if they might be effective for diseases such as Zika and the flu. COMPANIES: Inovio and others. RNA Vaccines Some researchers want to skip DNA and instead deliver messenger RNA into cells. The cells read the mRNA and make spike proteins that provoke an immune response. The biotech company Moderna recently completed a small safety trial with eight volunteers that showed promising early results against the coronavirus. Both RNA and DNA vaccines can be produced more quickly than traditional methods. EXAMPLES: There are no approved RNA vaccines, but they are in clinical trials for MERS and other diseases. COMPANIES: Moderna, Pfizer and BioNTech, CureVac and others. Viral Vector Vaccines Vaccines that use a virus to deliver coronavirus genes into cells. Vaccines Using Adenovirus or Other Viruses Viruses are very good at getting into cells'], response=None, multi_responses=None, reference='Prototype DNA vaccines based on the spike protein protected monkeys from the coronavirus by delivering genetic instructions for building a viral protein, which stimulated the immune system to make antibodies and mount defenses.', rubrics=None), synthesizer_name='single_hop_specifc_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='What role does Moderna play in the development of COVID-19 vaccines and what technologies do they use?', retrieved_contexts=None, reference_contexts=['. COMPANIES: Moderna, Pfizer and BioNTech, CureVac and others. Viral Vector Vaccines Vaccines that use a virus to deliver coronavirus genes into cells. Vaccines Using Adenovirus or Other Viruses Viruses are very good at getting into cells. Since the 1990s, researchers have been investigating how to use them to deliver genes into cells to immunize people against diseases. To create a coronavirus vaccine, several teams have added the spike protein gene to a virus called an adenovirus. The adenovirus slips into cells and unloads the gene. Because the adenovirus is missing one of its own genes, it cannot replicate and is therefore safe. EXAMPLES: Several virus vector vaccines are used to vaccinate animals against rabies and distemper. Johnson & Johnson has developed H.I.V. and Ebola vaccines using an adenovirus. Both have proven safe in humans and are now in efficacy trials. COMPANIES: Johnson & Johnson, CanSino, University of Oxford and others. Protein-Based Vaccines Vaccines that use a coronavirus protein or a protein fragment. Virus-Like Particle Vaccines Some vaccines are particles that contain pieces of viral proteins. They cant cause disease because they are not actual viruses, but they can still show the immune system what coronavirus proteins look like. EXAMPLES: The vaccine for HPV falls into this category. COMPANIES: Medicago, Doherty Institute and others. Recombinant Vaccines Yeast or other cells can be engineered to carry a viruss gene and spew out viral proteins, which are then harvested and put into a vaccine. A coronavirus vaccine of this design would contain whole spike proteins or small pieces of the protein'], response=None, multi_responses=None, reference='Moderna is one of the companies involved in the development of COVID-19 vaccines, alongside Pfizer, BioNTech, and others. They utilize various technologies, including viral vector vaccines and protein-based approaches, to enhance immunity against the coronavirus.', rubrics=None), synthesizer_name='single_hop_specifc_query_synthesizer'), TestsetSample(eval_sample=SingleTurnSample(user_input='How does the National Institute of Allergy and Infectious Diseases contribute to the development of COVID-19 vaccines?', retrieved_contexts=None, reference_contexts=['. COMPANIES: Medicago, Doherty Institute and others. Recombinant Vaccines Yeast or other cells can be engineered to carry a viruss gene and spew out viral proteins, which are then harvested and put into a vaccine. A coronavirus vaccine of this design would contain whole spike proteins or small pieces of the protein. EXAMPLES: This category includes some vaccines for shingles and hepatitis B. COMPANIES: Novavax and others. Sources: World Health Organization, National Institute of Allergy and Infectious Diseases, National Center for Biotechnology Information, NEJM'], response=None, multi_responses=None, reference='The National Institute of Allergy and Infectious Diseases is one of the sources that provide information and support for the development of COVID-19 vaccines, alongside organizations like the World Health Organization and the National Center for Biotechnology Information.', rubrics=None), synthesizer_name='single_hop_specifc_query_synthesizer')])

### 4B · 查看生成的测试集

转为 DataFrame 查看 `user_input`、`reference`、`reference_contexts` 和 `synthesizer_name`。

In [19]:
df = testset.to_pandas()
df

,user_input,reference_contexts,reference,synthesizer_name
0,What recent activities have Elon Musk and Ambe...,"[Elon Musk, Amber Heard Something's Fishy On W...",Elon Musk and Amber Heard were spotted on a su...,single_hop_specifc_query_synthesizer
1,How are scientists approaching the development...,[Scientists are developing more than 100 coron...,Scientists are developing more than 100 corona...,single_hop_specifc_query_synthesizer
2,How did DNA vaccines protect monkeys from the ...,[. DNA Vaccines A number of experimental coron...,Prototype DNA vaccines based on the spike prot...,single_hop_specifc_query_synthesizer
3,What role does Moderna play in the development...,"[. COMPANIES: Moderna, Pfizer and BioNTech, Cu...",Moderna is one of the companies involved in th...,single_hop_specifc_query_synthesizer
4,How does the National Institute of Allergy and...,"[. COMPANIES: Medicago, Doherty Institute and ...",The National Institute of Allergy and Infectio...,single_hop_specifc_query_synthesizer

In [20]:
for index in range(len(df)):
    print("index:", index)
    print("user_input:", df.iloc[index]['user_input'])
    print("reference_contexts:", df.iloc[index]['reference_contexts'])
    print("reference:", df.iloc[index]['reference'])
    print("synthesizer_name:", df.iloc[index]['synthesizer_name'])
    print("="*60)

index: 0
user_input: What recent activities have Elon Musk and Amber Heard engaged in while in WeHo?
reference_contexts: ['Elon Musk, Amber Heard Something\'s Fishy On Wrapped-Up Sushi Last we heard, Elon Musk and Amber Heard were "not back together" even though they kiss goodbye and dance real close ... sorry, we\'re not buying that now. Amber and Elon went on a sushi date Monday in WeHo, and looked like the full-blown hand-holding couple that\'s definitely on again. But that\'s only because that\'s exactly what they are -- no matter how many times they try to say they\'re not reunited. We broke the story ... Elon and Amber started hanging out again this past fall ... after announcing their split in the summer. Since then, they\'ve smooched and gone dancing together. If it looks like a reunited duck, walks like a reunited duck ... TMZ.com']
reference: Elon Musk and Amber Heard were spotted on a sushi date in WeHo, where they appeared to be a full-blown hand-holding couple, suggesting they are indeed back together despite claims that they are not.
synthesizer_name: single_hop_specifc_query_synthesizer
============================================================
index: 1
user_input: How are scientists approaching the development of coronavirus vaccines?
reference_contexts: ['Scientists are developing more than 100 coronavirus vaccines using a range of techniques, some of which are well-established and some of which have never been approved for medical use before. Most of these vaccines target the so-called spike proteins that cover the virus and help it invade human cells. The immune system can develop antibodies that latch onto spike proteins and stop the virus. A successful vaccine for the SARS-CoV-2 coronavirus would teach peoples immune systems to make antibodies against the virus without causing disease. Whole-Virus Vaccines Vaccines that modify the entire coronavirus to provoke an immune response. Inactivated and Live Attenuated Vaccines Most vaccines in use today incorporate an inactivated or weakened form of a virus that is not able to cause disease. When immune cells encounter them, they make antibodies. Making these vaccines means growing viruses and lots of them. Influenza vaccines are typically grown in chicken eggs, and other vaccines are grown in tanks full of floating cells. These procedures can take months to produce a batch of new vaccines. EXAMPLES: Conventional vaccines for influenza, chickenpox, measles, mumps and rubella all fall into this category. COMPANIES DEVELOPING SARS-COV-2 VACCINES: Sinovac and others. Genetic Vaccines Vaccines that use part of the coronaviruss genetic code. DNA Vaccines A number of experimental coronavirus vaccines dont deliver whole viruses. Instead, they deliver genetic instructions for building a viral protein. The protein can then stimulate the immune system to make antibodies and help mount other defenses against the coronavirus. One of these genetic approaches is known as a DNA vaccine. A circle of engineered DNA is delivered into cells']
reference: Scientists are developing more than 100 coronavirus vaccines using a range of techniques, some of which are well-established and some of which have never been approved for medical use before. Most of these vaccines target the spike proteins that cover the virus and help it invade human cells, allowing the immune system to develop antibodies that latch onto these proteins and stop the virus. A successful vaccine for the SARS-CoV-2 coronavirus would teach people's immune systems to make antibodies against the virus without causing disease.
synthesizer_name: single_hop_specifc_query_synthesizer
============================================================
index: 2
user_input: How did DNA vaccines protect monkeys from the coronavirus?
reference_contexts: ['. DNA Vaccines A number of experimental coronavirus vaccines dont deliver whole viruses. Instead, they deliver genetic instructions for building a viral protein. The protein can then stimulate the immune system to make antibodies and help mount other defenses against the coronavirus. One of these genetic approaches is known as a DNA vaccine. A circle of engineered DNA is delivered into cells. The cells read the viral gene, make a copy in a molecule called messenger RNA, and then use the mRNA to assemble viral proteins. The immune system detects the proteins and mounts defenses. Prototype DNA vaccines based on the spike protein protected monkeys from the coronavirus. EXAMPLES: DNA vaccines have been approved for veterinary cases such as canine melanoma and West Nile virus in horses. There are no approved DNA vaccines for use in humans, but researchers are running trials to see if they might be effective for diseases such as Zika and the flu. COMPANIES: Inovio and others. RNA Vaccines Some researchers want to skip DNA and instead deliver messenger RNA into cells. The cells read the mRNA and make spike proteins that provoke an immune response. The biotech company Moderna recently completed a small safety trial with eight volunteers that showed promising early results against the coronavirus. Both RNA and DNA vaccines can be produced more quickly than traditional methods. EXAMPLES: There are no approved RNA vaccines, but they are in clinical trials for MERS and other diseases. COMPANIES: Moderna, Pfizer and BioNTech, CureVac and others. Viral Vector Vaccines Vaccines that use a virus to deliver coronavirus genes into cells. Vaccines Using Adenovirus or Other Viruses Viruses are very good at getting into cells']
reference: Prototype DNA vaccines based on the spike protein protected monkeys from the coronavirus by delivering genetic instructions for building a viral protein, which stimulated the immune system to make antibodies and mount defenses.
synthesizer_name: single_hop_specifc_query_synthesizer
============================================================
index: 3
user_input: What role does Moderna play in the development of COVID-19 vaccines and what technologies do they use?
reference_contexts: ['. COMPANIES: Moderna, Pfizer and BioNTech, CureVac and others. Viral Vector Vaccines Vaccines that use a virus to deliver coronavirus genes into cells. Vaccines Using Adenovirus or Other Viruses Viruses are very good at getting into cells. Since the 1990s, researchers have been investigating how to use them to deliver genes into cells to immunize people against diseases. To create a coronavirus vaccine, several teams have added the spike protein gene to a virus called an adenovirus. The adenovirus slips into cells and unloads the gene. Because the adenovirus is missing one of its own genes, it cannot replicate and is therefore safe. EXAMPLES: Several virus vector vaccines are used to vaccinate animals against rabies and distemper. Johnson & Johnson has developed H.I.V. and Ebola vaccines using an adenovirus. Both have proven safe in humans and are now in efficacy trials. COMPANIES: Johnson & Johnson, CanSino, University of Oxford and others. Protein-Based Vaccines Vaccines that use a coronavirus protein or a protein fragment. Virus-Like Particle Vaccines Some vaccines are particles that contain pieces of viral proteins. They cant cause disease because they are not actual viruses, but they can still show the immune system what coronavirus proteins look like. EXAMPLES: The vaccine for HPV falls into this category. COMPANIES: Medicago, Doherty Institute and others. Recombinant Vaccines Yeast or other cells can be engineered to carry a viruss gene and spew out viral proteins, which are then harvested and put into a vaccine. A coronavirus vaccine of this design would contain whole spike proteins or small pieces of the protein']
reference: Moderna is one of the companies involved in the development of COVID-19 vaccines, alongside Pfizer, BioNTech, and others. They utilize various technologies, including viral vector vaccines and protein-based approaches, to enhance immunity against the coronavirus.
synthesizer_name: single_hop_specifc_query_synthesizer
============================================================
index: 4
user_input: How does the National Institute of Allergy and Infectious Diseases contribute to the development of COVID-19 vaccines?
reference_contexts: ['. COMPANIES: Medicago, Doherty Institute and others. Recombinant Vaccines Yeast or other cells can be engineered to carry a viruss gene and spew out viral proteins, which are then harvested and put into a vaccine. A coronavirus vaccine of this design would contain whole spike proteins or small pieces of the protein. EXAMPLES: This category includes some vaccines for shingles and hepatitis B. COMPANIES: Novavax and others. Sources: World Health Organization, National Institute of Allergy and Infectious Diseases, National Center for Biotechnology Information, NEJM']
reference: The National Institute of Allergy and Infectious Diseases is one of the sources that provide information and support for the development of COVID-19 vaccines, alongside organizations like the World Health Organization and the National Center for Biotechnology Information.
synthesizer_name: single_hop_specifc_query_synthesizer
============================================================

---

## Part 5 — 构建 RAG 流水线

将 chunk 写入 **FAISS** 向量库，构建检索 + 生成链路：

```
用户问题 → FAISS 检索 (top-5) → LLM 生成答案
```

后续可选叠加 **ContextualCompressionRetriever**（过滤 + 抽取 + Rerank），本 Notebook 基线先用纯向量检索。

In [22]:
from langchain_community.vectorstores import FAISS


vectorstore = FAISS.from_documents(
    documents = all_chunks2,
    embedding = cached_embedding
)

retriever = vectorstore.as_retriever(search_kwargs={"k": 5})

### 5B · 进阶：压缩 + Rerank 检索器（可选）

`ContextualCompressionRetriever` 在基础检索之上串联：

1. **LLMChainFilter** — 过滤不相关 chunk
2. **LLMChainExtractor** — 抽取与问题相关的核心句
3. **LLMListwiseRerank** — 对剩余文档重新排序

> 下方 cell 定义了该 retriever，基线评估默认使用上方简单 `retriever`。

In [ ]:
from langchain_classic.retrievers.document_compressors import (
    DocumentCompressorPipeline,
    LLMChainExtractor,
    LLMChainFilter,
    LLMListwiseRerank
)
from langchain_classic.retrievers import ContextualCompressionRetriever

# 过滤掉不相关或无用的文本 chunk
llm_filter = LLMChainFilter.from_llm(llm)
# 从 chunk 中抽取核心信息
llm_extractor = LLMChainExtractor.from_llm(llm)
# 文档压缩流水线
compressor_pipeline = DocumentCompressorPipeline(
    transformers=[llm_filter, llm_extractor]
)
# Reranker
reranker = LLMListwiseRerank.from_llm(llm)
compression_rerank_retriever = ContextualCompressionRetriever(
    base_retriever=retriever,
    base_compressor=compressor_pipeline,
    reranker=reranker
)

### 5C · RetrievalQA 链

使用严格约束的 Prompt：**仅依据 context 回答**，context 不足时回答 `"I don't know"`。这有助于在评估中区分「检索失败」与「生成幻觉」。

In [25]:
from langchain_core.prompts import PromptTemplate
from langchain_classic.chains.retrieval_qa.base import RetrievalQA


prompt_template = """
Answer strictly based on the context below.
Do NOT use information outside the context. 
If context does not contain the answer, say "I don't know".
Keep answer < 2 sentences.

Context:
{context}

Question:
{question}
"""

def get_qa_chain(retriever):
    return RetrievalQA.from_chain_type(
        llm=llm,
        chain_type="stuff",  
        retriever= retriever,
        return_source_documents=True, 
        chain_type_kwargs={"prompt": PromptTemplate(input_variables=["context","question"], template=prompt_template)}
    )
chain = get_qa_chain(retriever)

---

## Part 6 — 基线评估（Ragas 官方测试集）

对 Part 4 生成的测试集逐条调用 RAG，再用 Ragas 计算四项核心指标：

| 指标 | 衡量什么 |
|------|----------|
| **Context Precision** | 检索到的 context 是否相关 |
| **Context Recall** | 是否召回了回答所需的关键信息 |
| **Faithfulness** | 生成答案是否忠于 context（无幻觉） |
| **Answer Relevancy** | 答案与问题的相关程度 |

> 观察：当 reference 仅提及机构名称（如 NIAID）而 context 只有 "Sources: ..." 列表时，RAG 可能正确回答 "I don't know"，但 **Context Recall** 会偏低——这是评测集质量与检索粒度的典型张力。

In [29]:
responses_1 = [chain.invoke(x.eval_sample.user_input) for x in testset.samples]
responses_1

[{'query': 'What recent activities have Elon Musk and Amber Heard engaged in while in WeHo?',
  'result': 'They went on a sushi date and looked like a couple, holding hands and being close.',
  'source_documents': [Document(id='3e0aef2c-fe8e-4652-9bb8-033efd090ac8', metadata={'source': 0, 'doc_index': 0, 'chunk_index': 0, 'total_chunks': 1}, page_content='Elon Musk, Amber Heard Something\'s Fishy On Wrapped-Up Sushi Last we heard, Elon Musk and Amber Heard were "not back together" even though they kiss goodbye and dance real close ... sorry, we\'re not buying that now. Amber and Elon went on a sushi date Monday in WeHo, and looked like the full-blown hand-holding couple that\'s definitely on again. But that\'s only because that\'s exactly what they are -- no matter how many times they try to say they\'re not reunited. We broke the story ... Elon and Amber started hanging out again this past fall ... after announcing their split in the summer. Since then, they\'ve smooched and gone dancing together. If it looks like a reunited duck, walks like a reunited duck ... TMZ.com'),
   Document(id='fb3a0a77-a39a-4d20-b790-e00ace3da242', metadata={'source': 8, 'doc_index': 8, 'chunk_index': 0, 'total_chunks': 1}, page_content='Lil Pump Attention Record Companies ... $15 Mil or Take a Hike 1/27/2018 TMZ.com Lil Pump is super hot these days and he knows it ... because he ain\'t signing no recording contract for anything less than $15 mil. We got Pump leaving Avianne and Co. Jewelers Friday night in the Big Apple, where he says he dropped a quarter mil on bling. The 17-year-old rapper reportedly got out of his deal with Warner Bros. Records because it was never certified by a court ... something that\'s required when minors are involved. Pump\'s been getting offers, which makes sense. He\'s got several hit songs, including "Gucci Gang." He better sign a new deal fast ... he says he just bought a Rolls-Royce and is spending like crazy. Waiting for your permission to load the Instagram Media.'),
   Document(id='5afd8b03-3b7f-4822-85d7-872350399312', metadata={'source': 5, 'doc_index': 5, 'chunk_index': 9, 'total_chunks': 11}, page_content='. You dont set out wanting to know each others life, but you spend so much time with each other you cant help but know them. I knew, and I love the guy.ImageCredit...August Kryger for The New York TimesA Singular SeasonBy last August, Sams sexuality was an open secret here. He had told a professor he was gay and had become a genial presence at the SoCo Club in Columbia, a nightclub and cabaret that hosts regular drag shows, among other events.Marty Newman, SoCos owner and general manager, said Sam was open about who he was: a gay man and a football star. He was happy to talk sports with the bartenders and anyone else.No one felt the need to out him, Newman said. He was respected here and was allowed to be himself.In Sams senior season, Missouri finished 12-2 and won the Cotton Bowl. He made first-team all-American and was voted by his teammates as Missouris most valuable player.On Monday, Pinkel tried to put in words a singular season that began with his noisiest players startling announcement, and ended with dozens of men standing by their teammate in the national spotlight.Pretty cool, was the best he could do.On Saturday night, over Chinese food at the home of his publicist, Howard Bragman, Sam was joined by an exclusive group: the fraternity of publicly gay athletes and their peers who have made a cause of supporting them.Dave Kopay and Wade Davis, who came out as gay after retiring from professional football, and Bill Bean, who did so after retiring from professional baseball, were there, along with Brendon Ayanbadejo and Chris Kluwe, two former N'),
   Document(id='0e2bb9f5-d4ab-4c4d-8a13-9ed022b6384f', metadata={'source': 4, 'doc_index': 4, 'chunk_index': 0, 'total_chunks': 10}, page_content='Credit...Jim Wilson/The New York TimesJune 30, 2018WASHINGTON On the final day of the Supreme Court term last week, Justice Elena Kagan sounded an alarm.The courts five conservative members, citing the First Amendment, had just dealt public unions a devastating blow. The day before, the same majority had used the First Amendment to reject a California law requiring religiously oriented crisis pregnancy centers to provide women with information about abortion.Conservatives, said Justice Kagan, who is part of the courts four-member liberal wing, were weaponizing the First Amendment.The two decisions were the latest in a stunning run of victories for a conservative agenda that has increasingly been built on the foundation of free speech. Conservative groups, borrowing and building on arguments developed by liberals, have used the First Amendment to justify unlimited campaign spending, discrimination against gay couples and attacks on the regulation of tobacco, pharmaceuticals and guns.The right, which had for years been hostile to and very nervous about a strong First Amendment, has rediscovered it, said Burt Neuborne, a law professor at New York University.The Citizens United campaign finance case, for instance, was decided on free-speech grounds, with the five-justice conservative majority ruling that the First Amendment protects unlimited campaign spending by corporations. The government, the majority said, has no business regulating political speech.The dissenters responded that the First Amendment did not require allowing corporate money to flood the political marketplace and corrupt democracy.The libertarian position has become dominant on the right on First Amendment issues, said Ilya Shapiro, a lawyer with the Cato Institute. It simply means that we should be skeptical of government attempts to regulate speech. That used to be an uncontroversial and nonideological point'),
   Document(id='d95aeba6-90a8-4a43-b087-02ca2dc56898', metadata={'source': 5, 'doc_index': 5, 'chunk_index': 10, 'total_chunks': 11}, page_content='.Dave Kopay and Wade Davis, who came out as gay after retiring from professional football, and Bill Bean, who did so after retiring from professional baseball, were there, along with Brendon Ayanbadejo and Chris Kluwe, two former N.F.L. players who have been outspoken in their support of gay rights.It was a chance to celebrate Sam on his last night of relative anonymity, but it was also a way to tell him about the world he was diving into.Kopay, a 71-year-old former running back, playfully punched Sam a couple of times to emphasize just how intensely he would have to work. He also reminded Sam that if they had been freshmen together in 1960, Sam, as a black man, would not have been entirely welcome. (Norris Stevenson broke the color barrier for Missouri in 1957.)Well, youre just taking another step forward now, Kopay said.Kluwe told him he would not have many problems with players. Theyre there to play football, he said.The men in charge will pose problems, Kluwe said. Its the general managers and coaches who are going to say its a distraction.Then theres the public at large, the millions of sports fans who will soon see a publicly gay player standing tall on an N.F.L. teams defensive line. It is too early to know how they will react, but perhaps the evolution in Sams own family offers a clue.I believe in a persons destiny, his aunt Geraldine Sam said. If thats the way he is, Im not trying to put my religious beliefs on anyone. I respect people for who they are, not who we want them to be.')]},
 {'query': 'How are scientists approaching the development of coronavirus vaccines?',
  'result': 'Scientists are developing more than 100 coronavirus vaccines using a range of techniques, including well-established methods like inactivated vaccines and innovative approaches such as genetic, viral vector, protein-based, and recombinant vaccines.',
  'source_documents': [Document(id='8944d89e-92a0-418b-bee6-8e6a6ef88436', metadata={'source': 1, 'doc_index': 1, 'chunk_index': 0, 'total_chunks': 4}, page_content='Scientists are developing more than 100 coronavirus vaccines using a range of techniques, some of which are well-established and some of which have never been approved for medical use before. Most of these vaccines target the so-called spike proteins that cover the virus and help it invade human cells. The immune system can develop antibodies that latch onto spike proteins and stop the virus. A successful vaccine for the SARS-CoV-2 coronavirus would teach peoples immune systems to make antibodies against the virus without causing disease. Whole-Virus Vaccines Vaccines that modify the entire coronavirus to provoke an immune response. Inactivated and Live Attenuated Vaccines Most vaccines in use today incorporate an inactivated or weakened form of a virus that is not able to cause disease. When immune cells encounter them, they make antibodies. Making these vaccines means growing viruses and lots of them. Influenza vaccines are typically grown in chicken eggs, and other vaccines are grown in tanks full of floating cells. These procedures can take months to produce a batch of new vaccines. EXAMPLES: Conventional vaccines for influenza, chickenpox, measles, mumps and rubella all fall into this category. COMPANIES DEVELOPING SARS-COV-2 VACCINES: Sinovac and others. Genetic Vaccines Vaccines that use part of the coronaviruss genetic code. DNA Vaccines A number of experimental coronavirus vaccines dont deliver whole viruses. Instead, they deliver genetic instructions for building a viral protein. The protein can then stimulate the immune system to make antibodies and help mount other defenses against the coronavirus. One of these genetic approaches is known as a DNA vaccine. A circle of engineered DNA is delivered into cells'),
   Document(id='bf898b56-dcdc-44c4-be28-6d64107f9924', metadata={'source': 1, 'doc_index': 1, 'chunk_index': 1, 'total_chunks': 4}, page_content='. DNA Vaccines A number of experimental coronavirus vaccines dont deliver whole viruses. Instead, they deliver genetic instructions for building a viral protein. The protein can then stimulate the immune system to make antibodies and help mount other defenses against the coronavirus. One of these genetic approaches is known as a DNA vaccine. A circle of engineered DNA is delivered into cells. The cells read the viral gene, make a copy in a molecule called messenger RNA, and then use the mRNA to assemble viral proteins. The immune system detects the proteins and mounts defenses. Prototype DNA vaccines based on the spike protein protected monkeys from the coronavirus. EXAMPLES: DNA vaccines have been approved for veterinary cases such as canine melanoma and West Nile virus in horses. There are no approved DNA vaccines for use in humans, but researchers are running trials to see if they might be effective for diseases such as Zika and the flu. COMPANIES: Inovio and others. RNA Vaccines Some researchers want to skip DNA and instead deliver messenger RNA into cells. The cells read the mRNA and make spike proteins that provoke an immune response. The biotech company Moderna recently completed a small safety trial with eight volunteers that showed promising early results against the coronavirus. Both RNA and DNA vaccines can be produced more quickly than traditional methods. EXAMPLES: There are no approved RNA vaccines, but they are in clinical trials for MERS and other diseases. COMPANIES: Moderna, Pfizer and BioNTech, CureVac and others. Viral Vector Vaccines Vaccines that use a virus to deliver coronavirus genes into cells. Vaccines Using Adenovirus or Other Viruses Viruses are very good at getting into cells'),
   Document(id='cd39d8bb-847b-44f6-9374-e2bb63b3d024', metadata={'source': 1, 'doc_index': 1, 'chunk_index': 2, 'total_chunks': 4}, page_content='. COMPANIES: Moderna, Pfizer and BioNTech, CureVac and others. Viral Vector Vaccines Vaccines that use a virus to deliver coronavirus genes into cells. Vaccines Using Adenovirus or Other Viruses Viruses are very good at getting into cells. Since the 1990s, researchers have been investigating how to use them to deliver genes into cells to immunize people against diseases. To create a coronavirus vaccine, several teams have added the spike protein gene to a virus called an adenovirus. The adenovirus slips into cells and unloads the gene. Because the adenovirus is missing one of its own genes, it cannot replicate and is therefore safe. EXAMPLES: Several virus vector vaccines are used to vaccinate animals against rabies and distemper. Johnson & Johnson has developed H.I.V. and Ebola vaccines using an adenovirus. Both have proven safe in humans and are now in efficacy trials. COMPANIES: Johnson & Johnson, CanSino, University of Oxford and others. Protein-Based Vaccines Vaccines that use a coronavirus protein or a protein fragment. Virus-Like Particle Vaccines Some vaccines are particles that contain pieces of viral proteins. They cant cause disease because they are not actual viruses, but they can still show the immune system what coronavirus proteins look like. EXAMPLES: The vaccine for HPV falls into this category. COMPANIES: Medicago, Doherty Institute and others. Recombinant Vaccines Yeast or other cells can be engineered to carry a viruss gene and spew out viral proteins, which are then harvested and put into a vaccine. A coronavirus vaccine of this design would contain whole spike proteins or small pieces of the protein'),
   Document(id='b84ce172-bf59-4b93-b856-acad027d65ef', metadata={'source': 1, 'doc_index': 1, 'chunk_index': 3, 'total_chunks': 4}, page_content='. COMPANIES: Medicago, Doherty Institute and others. Recombinant Vaccines Yeast or other cells can be engineered to carry a viruss gene and spew out viral proteins, which are then harvested and put into a vaccine. A coronavirus vaccine of this design would contain whole spike proteins or small pieces of the protein. EXAMPLES: This category includes some vaccines for shingles and hepatitis B. COMPANIES: Novavax and others. Sources: World Health Organization, National Institute of Allergy and Infectious Diseases, National Center for Biotechnology Information, NEJM'),
   Document(id='7be148e7-b10d-4233-996d-f2828dbef8ca', metadata={'source': 3, 'doc_index': 3, 'chunk_index': 1, 'total_chunks': 4}, page_content='. The tests might also be used to identify potential donors of convalescent plasma, an approach in which blood plasma containing antibodies from a recovered individual is used to treat a Covid-19 patient, the F.D.A. said.The highly infectious disease has now killed nearly 70,000 people and sickened more than 1.1 million in the United States alone.While 12 companies have been given F.D.A. clearance to sell the antibody tests, many other products do not have agency authorization. The result has been a confusing landscape in which tests by established companies such as Abbott Laboratories, Cellex and most recently, Roche Diagnostics, are competing with unapproved tests made by unknown companies and sold by U.S. distributors with spotty track records. The F.D.A. has blocked imports of some antibody tests at the U.S. border, and has ordered some distributors to revise claims about what individuals can learn from them, or halt sales.House Democrats Raja Krishnamoorthi, of Illinois, and Rosa DeLauro, of Connecticut, have both criticized the agency for its handling of the matter as has Representative Lloyd Doggett, Democrat of Texas.The administrations original serology testing policy, which allowed tests on the market with no F.D.A. review, felt like an overreaction to the criticism they faced for their slow rollout of molecular tests, Mr. Krishnamoorthi said. But F.D.A. went too far, completely abrogating regulatory responsibility.Overseeing development of coronavirus tests has been rocky from the start, with President Trump and others urging the agency to relax rules for commercial tests')]},
 {'query': 'How did DNA vaccines protect monkeys from the coronavirus?',
  'result': 'Prototype DNA vaccines based on the spike protein protected monkeys from the coronavirus by stimulating the immune system to produce antibodies against the virus.',
  'source_documents': [Document(id='bf898b56-dcdc-44c4-be28-6d64107f9924', metadata={'source': 1, 'doc_index': 1, 'chunk_index': 1, 'total_chunks': 4}, page_content='. DNA Vaccines A number of experimental coronavirus vaccines dont deliver whole viruses. Instead, they deliver genetic instructions for building a viral protein. The protein can then stimulate the immune system to make antibodies and help mount other defenses against the coronavirus. One of these genetic approaches is known as a DNA vaccine. A circle of engineered DNA is delivered into cells. The cells read the viral gene, make a copy in a molecule called messenger RNA, and then use the mRNA to assemble viral proteins. The immune system detects the proteins and mounts defenses. Prototype DNA vaccines based on the spike protein protected monkeys from the coronavirus. EXAMPLES: DNA vaccines have been approved for veterinary cases such as canine melanoma and West Nile virus in horses. There are no approved DNA vaccines for use in humans, but researchers are running trials to see if they might be effective for diseases such as Zika and the flu. COMPANIES: Inovio and others. RNA Vaccines Some researchers want to skip DNA and instead deliver messenger RNA into cells. The cells read the mRNA and make spike proteins that provoke an immune response. The biotech company Moderna recently completed a small safety trial with eight volunteers that showed promising early results against the coronavirus. Both RNA and DNA vaccines can be produced more quickly than traditional methods. EXAMPLES: There are no approved RNA vaccines, but they are in clinical trials for MERS and other diseases. COMPANIES: Moderna, Pfizer and BioNTech, CureVac and others. Viral Vector Vaccines Vaccines that use a virus to deliver coronavirus genes into cells. Vaccines Using Adenovirus or Other Viruses Viruses are very good at getting into cells'),
   Document(id='8944d89e-92a0-418b-bee6-8e6a6ef88436', metadata={'source': 1, 'doc_index': 1, 'chunk_index': 0, 'total_chunks': 4}, page_content='Scientists are developing more than 100 coronavirus vaccines using a range of techniques, some of which are well-established and some of which have never been approved for medical use before. Most of these vaccines target the so-called spike proteins that cover the virus and help it invade human cells. The immune system can develop antibodies that latch onto spike proteins and stop the virus. A successful vaccine for the SARS-CoV-2 coronavirus would teach peoples immune systems to make antibodies against the virus without causing disease. Whole-Virus Vaccines Vaccines that modify the entire coronavirus to provoke an immune response. Inactivated and Live Attenuated Vaccines Most vaccines in use today incorporate an inactivated or weakened form of a virus that is not able to cause disease. When immune cells encounter them, they make antibodies. Making these vaccines means growing viruses and lots of them. Influenza vaccines are typically grown in chicken eggs, and other vaccines are grown in tanks full of floating cells. These procedures can take months to produce a batch of new vaccines. EXAMPLES: Conventional vaccines for influenza, chickenpox, measles, mumps and rubella all fall into this category. COMPANIES DEVELOPING SARS-COV-2 VACCINES: Sinovac and others. Genetic Vaccines Vaccines that use part of the coronaviruss genetic code. DNA Vaccines A number of experimental coronavirus vaccines dont deliver whole viruses. Instead, they deliver genetic instructions for building a viral protein. The protein can then stimulate the immune system to make antibodies and help mount other defenses against the coronavirus. One of these genetic approaches is known as a DNA vaccine. A circle of engineered DNA is delivered into cells'),

In [32]:
for r in responses_1:
    print(r['result'])
    print('='*60)

They went on a sushi date and looked like a couple, holding hands and being close.
============================================================
Scientists are developing more than 100 coronavirus vaccines using a range of techniques, including well-established methods like inactivated vaccines and innovative approaches such as genetic, viral vector, protein-based, and recombinant vaccines.
============================================================
Prototype DNA vaccines based on the spike protein protected monkeys from the coronavirus by stimulating the immune system to produce antibodies against the virus.
============================================================
Moderna is involved in developing RNA vaccines for COVID-19, delivering messenger RNA into cells to provoke an immune response.
============================================================
I don't know.
============================================================

### 6B · 组装 EvaluationDataset 并调用 `evaluate()`

In [33]:
from ragas.metrics import answer_relevancy, faithfulness, context_recall, ContextPrecision

metrics=[ContextPrecision(), context_recall, faithfulness, answer_relevancy]

In [34]:
from ragas import EvaluationDataset
from ragas import evaluate

def gen_evaluate_dataset(testset, responses):
    hfset = testset.to_hf_dataset()
    records = []
    for sample, resp in zip(hfset, responses):
        records.append({
            "user_input": sample['user_input'],
            "reference": sample['reference'],
            "response": resp['result'],
            "retrieved_contexts": [d.page_content for d in resp['source_documents']],
        })
    eval_dataset = EvaluationDataset.from_dict(records)
    return eval_dataset

In [38]:
eval_dataset = gen_evaluate_dataset(testset, responses_1)

In [39]:
eval_results  = evaluate(
    dataset=eval_dataset, 
    metrics=metrics,
    llm=llm,
    embeddings=cached_embedding
)

Evaluating:   0%|          | 0/20 [00:00<?, ?it/s]

In [42]:
eval_results

{'context_precision': 0.8500, 'context_recall': 0.8000, 'faithfulness': 0.7000, 'answer_relevancy': 0.6041}

In [45]:
eval_results['answer_relevancy']

[np.float64(0.6516946369591511),
 np.float64(0.8093610615271499),
 np.float64(0.7815123294287667),
 np.float64(0.7777963744149187),
 np.float64(0.0)]

In [46]:
responses_1[-1]

{'query': 'How does the National Institute of Allergy and Infectious Diseases contribute to the development of COVID-19 vaccines?',
 'result': "I don't know.",
 'source_documents': [Document(id='8944d89e-92a0-418b-bee6-8e6a6ef88436', metadata={'source': 1, 'doc_index': 1, 'chunk_index': 0, 'total_chunks': 4}, page_content='Scientists are developing more than 100 coronavirus vaccines using a range of techniques, some of which are well-established and some of which have never been approved for medical use before. Most of these vaccines target the so-called spike proteins that cover the virus and help it invade human cells. The immune system can develop antibodies that latch onto spike proteins and stop the virus. A successful vaccine for the SARS-CoV-2 coronavirus would teach peoples immune systems to make antibodies against the virus without causing disease. Whole-Virus Vaccines Vaccines that modify the entire coronavirus to provoke an immune response. Inactivated and Live Attenuated Vaccines Most vaccines in use today incorporate an inactivated or weakened form of a virus that is not able to cause disease. When immune cells encounter them, they make antibodies. Making these vaccines means growing viruses and lots of them. Influenza vaccines are typically grown in chicken eggs, and other vaccines are grown in tanks full of floating cells. These procedures can take months to produce a batch of new vaccines. EXAMPLES: Conventional vaccines for influenza, chickenpox, measles, mumps and rubella all fall into this category. COMPANIES DEVELOPING SARS-COV-2 VACCINES: Sinovac and others. Genetic Vaccines Vaccines that use part of the coronaviruss genetic code. DNA Vaccines A number of experimental coronavirus vaccines dont deliver whole viruses. Instead, they deliver genetic instructions for building a viral protein. The protein can then stimulate the immune system to make antibodies and help mount other defenses against the coronavirus. One of these genetic approaches is known as a DNA vaccine. A circle of engineered DNA is delivered into cells'),
  Document(id='b84ce172-bf59-4b93-b856-acad027d65ef', metadata={'source': 1, 'doc_index': 1, 'chunk_index': 3, 'total_chunks': 4}, page_content='. COMPANIES: Medicago, Doherty Institute and others. Recombinant Vaccines Yeast or other cells can be engineered to carry a viruss gene and spew out viral proteins, which are then harvested and put into a vaccine. A coronavirus vaccine of this design would contain whole spike proteins or small pieces of the protein. EXAMPLES: This category includes some vaccines for shingles and hepatitis B. COMPANIES: Novavax and others. Sources: World Health Organization, National Institute of Allergy and Infectious Diseases, National Center for Biotechnology Information, NEJM'),
  Document(id='cd39d8bb-847b-44f6-9374-e2bb63b3d024', metadata={'source': 1, 'doc_index': 1, 'chunk_index': 2, 'total_chunks': 4}, page_content='. COMPANIES: Moderna, Pfizer and BioNTech, CureVac and others. Viral Vector Vaccines Vaccines that use a virus to deliver coronavirus genes into cells. Vaccines Using Adenovirus or Other Viruses Viruses are very good at getting into cells. Since the 1990s, researchers have been investigating how to use them to deliver genes into cells to immunize people against diseases. To create a coronavirus vaccine, several teams have added the spike protein gene to a virus called an adenovirus. The adenovirus slips into cells and unloads the gene. Because the adenovirus is missing one of its own genes, it cannot replicate and is therefore safe. EXAMPLES: Several virus vector vaccines are used to vaccinate animals against rabies and distemper. Johnson & Johnson has developed H.I.V. and Ebola vaccines using an adenovirus. Both have proven safe in humans and are now in efficacy trials. COMPANIES: Johnson & Johnson, CanSino, University of Oxford and others. Protein-Based Vaccines Vaccines that use a coronavirus protein or a protein fragment. Virus-Like Particle Vaccines Some vaccines are particles that contain pieces of viral proteins. They cant cause disease because they are not actual viruses, but they can still show the immune system what coronavirus proteins look like. EXAMPLES: The vaccine for HPV falls into this category. COMPANIES: Medicago, Doherty Institute and others. Recombinant Vaccines Yeast or other cells can be engineered to carry a viruss gene and spew out viral proteins, which are then harvested and put into a vaccine. A coronavirus vaccine of this design would contain whole spike proteins or small pieces of the protein'),
  Document(id='bf898b56-dcdc-44c4-be28-6d64107f9924', metadata={'source': 1, 'doc_index': 1, 'chunk_index': 1, 'total_chunks': 4}, page_content='. DNA Vaccines A number of experimental coronavirus vaccines dont deliver whole viruses. Instead, they deliver genetic instructions for building a viral protein. The protein can then stimulate the immune system to make antibodies and help mount other defenses against the coronavirus. One of these genetic approaches is known as a DNA vaccine. A circle of engineered DNA is delivered into cells. The cells read the viral gene, make a copy in a molecule called messenger RNA, and then use the mRNA to assemble viral proteins. The immune system detects the proteins and mounts defenses. Prototype DNA vaccines based on the spike protein protected monkeys from the coronavirus. EXAMPLES: DNA vaccines have been approved for veterinary cases such as canine melanoma and West Nile virus in horses. There are no approved DNA vaccines for use in humans, but researchers are running trials to see if they might be effective for diseases such as Zika and the flu. COMPANIES: Inovio and others. RNA Vaccines Some researchers want to skip DNA and instead deliver messenger RNA into cells. The cells read the mRNA and make spike proteins that provoke an immune response. The biotech company Moderna recently completed a small safety trial with eight volunteers that showed promising early results against the coronavirus. Both RNA and DNA vaccines can be produced more quickly than traditional methods. EXAMPLES: There are no approved RNA vaccines, but they are in clinical trials for MERS and other diseases. COMPANIES: Moderna, Pfizer and BioNTech, CureVac and others. Viral Vector Vaccines Vaccines that use a virus to deliver coronavirus genes into cells. Vaccines Using Adenovirus or Other Viruses Viruses are very good at getting into cells'),
  Document(id='7be148e7-b10d-4233-996d-f2828dbef8ca', metadata={'source': 3, 'doc_index': 3, 'chunk_index': 1, 'total_chunks': 4}, page_content='. The tests might also be used to identify potential donors of convalescent plasma, an approach in which blood plasma containing antibodies from a recovered individual is used to treat a Covid-19 patient, the F.D.A. said.The highly infectious disease has now killed nearly 70,000 people and sickened more than 1.1 million in the United States alone.While 12 companies have been given F.D.A. clearance to sell the antibody tests, many other products do not have agency authorization. The result has been a confusing landscape in which tests by established companies such as Abbott Laboratories, Cellex and most recently, Roche Diagnostics, are competing with unapproved tests made by unknown companies and sold by U.S. distributors with spotty track records. The F.D.A. has blocked imports of some antibody tests at the U.S. border, and has ordered some distributors to revise claims about what individuals can learn from them, or halt sales.House Democrats Raja Krishnamoorthi, of Illinois, and Rosa DeLauro, of Connecticut, have both criticized the agency for its handling of the matter as has Representative Lloyd Doggett, Democrat of Texas.The administrations original serology testing policy, which allowed tests on the market with no F.D.A. review, felt like an overreaction to the criticism they faced for their slow rollout of molecular tests, Mr. Krishnamoorthi said. But F.D.A. went too far, completely abrogating regulatory responsibility.Overseeing development of coronavirus tests has been rocky from the start, with President Trump and others urging the agency to relax rules for commercial tests')]}

---

## Part 7 — 自定义 QA 生成（可控方案）

相比 Ragas 全自动流程，这里用 **LLM 逐 chunk 生成 QA**，优势：

- 逻辑透明、易于调试
- 可控制每文档 / 每 chunk 的 QA 数量
- `reference_contexts` 精确绑定到单个 chunk（评测更干净）

**策略：**

- 每个文档最多 `max_qa_per_doc=1` 条
- 每个 chunk 最多 `max_qa_per_chunk=1` 条
- LLM 输出 JSON 数组 `[{"query": "...", "answer": "..."}]`

生成后包装为 Ragas `Testset`，与 Part 4 格式对齐，便于同口径对比。

In [53]:
import json

def generate_qa_from_chunks(llm, chunks, target_qa_count = 10, max_qa_per_doc=1, max_qa_per_chunk=1) -> list[dict]:
    all_qa = []
    doc_qa_counter = {}
    for chunk in chunks:
        source = chunk.metadata['source']
        doc_qa_count = doc_qa_counter.get(source, 0)
        remaining_for_doc = max_qa_per_doc - doc_qa_counter.get(source, 0)
        if remaining_for_doc <= 0:
            continue
        max_qa=min(max_qa_per_chunk, remaining_for_doc)
        qas = generate_qa_from_chunk(llm, chunk, max_qa_per_chunk=max_qa)
        print("Generated QA count:", len(qas), chunk.metadata['source'], chunk.metadata['doc_index'], chunk.metadata['chunk_index'])
        all_qa.extend(qas)
        doc_qa_counter[source] = doc_qa_count + len(qas)
        if len(all_qa) >= target_qa_count:
            break
    return all_qa[:target_qa_count]


def generate_qa_from_chunk(llm, doc_chunk, max_qa_per_chunk: int = 1) -> list[dict]:
    prompt = f"""
You are an assistant. Analyze the text below and generate up to {max_qa_per_chunk} question(s)
with their answers based strictly on the text.

If the text is unsuitable for generating QA, return an empty JSON array.

Always output ONLY in JSON array format, like:
[
    {{"query": "question1", "answer": "answer1"}},
    ...
]

Text:
{doc_chunk.page_content}
"""
    response = llm.invoke(prompt).content
    try:
        raw_qas = json.loads(response)
    except Exception as e:
        print("Failed to parse LLM output:", e)
        print("LLM output:", response)
        return []
    
    results = []
    for qa in raw_qas:
        if "query" not in qa or "answer" not in qa:
            continue
        results.append({
            "user_input": qa["query"],
            "reference": qa["answer"],
            "retrieved_contexts": [doc_chunk.page_content],
            "doc_index": doc_chunk.metadata['doc_index'],
            "chunk_index": doc_chunk.metadata['chunk_index'],
            "synthesizer_name": "single_hop_specifc_query_synthesizer"

        })
    return results

In [54]:
from ragas.testset.synthesizers.testset_schema import Testset

testset_l = generate_qa_from_chunks(llm, all_chunks2, target_qa_count=5)
testset3 = Testset.from_list(testset_l)

Generated QA count: 1 0 0 0
Generated QA count: 1 1 1 0
Generated QA count: 1 2 2 0
Generated QA count: 1 3 3 0
Generated QA count: 1 4 4 0

---

## Part 8 — 对比评估：自定义测试集

用同一套 RAG 流水线评估 Part 7 生成的测试集，与 Part 6 结果对比。

**预期差异：**

- 自定义方案的 `reference_contexts` 通常只有 **1 个 chunk**，Context Recall / Faithfulness 往往更高
- Ragas 自动生成的 question 可能更「绕」，对检索要求更高

对比两次 `eval_results` 的各指标均值，选择更适合你业务的测试集生成策略。

In [55]:
responses_3 = [chain.invoke(x.eval_sample.user_input) for x in testset3.samples]
responses_3

[{'query': 'Are Elon Musk and Amber Heard currently back together according to the text?',
  'result': 'Yes, according to the text, Elon Musk and Amber Heard are effectively back together, as they are described as "the full-blown hand-holding couple that\'s definitely on again" despite claims they are not reunited.',
  'source_documents': [Document(id='3e0aef2c-fe8e-4652-9bb8-033efd090ac8', metadata={'source': 0, 'doc_index': 0, 'chunk_index': 0, 'total_chunks': 1}, page_content='Elon Musk, Amber Heard Something\'s Fishy On Wrapped-Up Sushi Last we heard, Elon Musk and Amber Heard were "not back together" even though they kiss goodbye and dance real close ... sorry, we\'re not buying that now. Amber and Elon went on a sushi date Monday in WeHo, and looked like the full-blown hand-holding couple that\'s definitely on again. But that\'s only because that\'s exactly what they are -- no matter how many times they try to say they\'re not reunited. We broke the story ... Elon and Amber started hanging out again this past fall ... after announcing their split in the summer. Since then, they\'ve smooched and gone dancing together. If it looks like a reunited duck, walks like a reunited duck ... TMZ.com'),
   Document(id='ee2af6e2-5c79-4bde-9c65-d7b53907933c', metadata={'source': 7, 'doc_index': 7, 'chunk_index': 3, 'total_chunks': 4}, page_content='.Smaller app makers, normally wary of angering the tech giants, have found strength in numbers. In September, more than a dozen of them, including the music streaming service Spotify, the dating service Match Group and the Bluetooth tracking device maker Tile, formed a nonprofit group called Coalition for App Fairness to push for changes to the app stores.In a hearing last month, Apple said it was willing to reinstate Fortnite to its app store before a trial if Epic would return to complying with its rules. Judge Gonzalez Rogers proposed an arrangement that would put Apples fees from Fortnite in an escrow account until after the trial. But Epic refused, arguing that doing so would be complying with a contract it views as unlawful.I didnt buy that argument before, Judge Gonzalez Rogers said in the hearing. Im not particularly impressed with it now.'),
   Document(id='ce33243d-0ce6-42c0-a9dc-36ac195796da', metadata={'source': 7, 'doc_index': 7, 'chunk_index': 2, 'total_chunks': 4}, page_content='. We came gradually to the realization that we had to fight this, not just by words, but also by really broad actions.Epic has said it wants Apple to change its requirements that apps use its payment system and shell out a 30 percent fee. It also wants to operate its own app store within Apples.The companies began fighting in August, when Epic violated Apples and Googles rules by directing Fortnite users to its own payments service. Apple and Google responded by pulling Fortnite from their app stores. Epic then sued both companies, arguing they were breaking antitrust laws.Apple later also cut off its support for Unreal Engine, Epics software development tool that is used by thousands of game makers. Judge Gonzalez Rogers said on Friday that Apple must continue supporting Unreal Engine and could not retaliate against any of Epics other affiliated apps or products.The fight has escalated over the past few weeks. Apple has accused Epic of seeking a special deal for itself, while Epic has accused Apple of cherry-picking out-of-context emails in its legal response.Other companies have used the battle to criticize Apple. Microsoft filed a declaration in support of Epic and has announced a set of developer-friendly principles for its own app store. Facebook has also recently called out Apples 30 percent app fees.Smaller app makers, normally wary of angering the tech giants, have found strength in numbers. In September, more than a dozen of them, including the music streaming service Spotify, the dating service Match Group and the Bluetooth tracking device maker Tile, formed a nonprofit group called Coalition for App Fairness to push for changes to the app stores'),
   Document(id='d9687ca3-e89c-43c2-addd-fde6132c489b', metadata={'source': 7, 'doc_index': 7, 'chunk_index': 0, 'total_chunks': 4}, page_content='Fortnites parent company, Epic Games, had broken its contract with Apple, a federal judge found. The case goes to trial next year.Credit...Brian Finke for The New York TimesPublished Oct. 9, 2020Updated Sept. 10, 2021SAN FRANCISCO A federal judge ruled on Friday that Apple did not need to reinstate the popular video game Fortnite in its App Store, in a blow to Fortnites parent company, Epic Games, which is locked in an antitrust battle with the tech giant over its app store fees and rules.Judge Yvonne Gonzalez Rogers of the Northern District of California said in her ruling that Apples ban of the game could continue because Epic had violated its contract with Apple. There is significant public interest in requiring companies to adhere to contracts or resolve disputes through the normal course, she wrote.But Judge Gonzales Rogers also said that Apple could not ban Unreal Engine, Epics developer tools, from its platforms because of the potential significant damage to both developers and gamers who rely on the software.The mixed ruling showed the high cost of taking on a tech behemoth like Apple, even for an established company like Epic. The 116 million people who have accessed Fortnite through Apples systems will continue to be kept away while Epic and Apple prepare for a trial in the case, which is scheduled for May.An Epic spokeswoman said the company is grateful that Apple will continue to be barred from retaliating against Unreal Engine and our game development customers. Epic will continue developing for Apples platforms and pursue all avenues to end Apples anti-competitive behavior, she said'),
   Document(id='0e2bb9f5-d4ab-4c4d-8a13-9ed022b6384f', metadata={'source': 4, 'doc_index': 4, 'chunk_index': 0, 'total_chunks': 10}, page_content='Credit...Jim Wilson/The New York TimesJune 30, 2018WASHINGTON On the final day of the Supreme Court term last week, Justice Elena Kagan sounded an alarm.The courts five conservative members, citing the First Amendment, had just dealt public unions a devastating blow. The day before, the same majority had used the First Amendment to reject a California law requiring religiously oriented crisis pregnancy centers to provide women with information about abortion.Conservatives, said Justice Kagan, who is part of the courts four-member liberal wing, were weaponizing the First Amendment.The two decisions were the latest in a stunning run of victories for a conservative agenda that has increasingly been built on the foundation of free speech. Conservative groups, borrowing and building on arguments developed by liberals, have used the First Amendment to justify unlimited campaign spending, discrimination against gay couples and attacks on the regulation of tobacco, pharmaceuticals and guns.The right, which had for years been hostile to and very nervous about a strong First Amendment, has rediscovered it, said Burt Neuborne, a law professor at New York University.The Citizens United campaign finance case, for instance, was decided on free-speech grounds, with the five-justice conservative majority ruling that the First Amendment protects unlimited campaign spending by corporations. The government, the majority said, has no business regulating political speech.The dissenters responded that the First Amendment did not require allowing corporate money to flood the political marketplace and corrupt democracy.The libertarian position has become dominant on the right on First Amendment issues, said Ilya Shapiro, a lawyer with the Cato Institute. It simply means that we should be skeptical of government attempts to regulate speech. That used to be an uncontroversial and nonideological point')]},
 {'query': 'What do most coronavirus vaccines target to help prevent infection?',
  'result': 'Most coronavirus vaccines target the spike proteins that cover the virus to help prevent infection.',
  'source_documents': [Document(id='8944d89e-92a0-418b-bee6-8e6a6ef88436', metadata={'source': 1, 'doc_index': 1, 'chunk_index': 0, 'total_chunks': 4}, page_content='Scientists are developing more than 100 coronavirus vaccines using a range of techniques, some of which are well-established and some of which have never been approved for medical use before. Most of these vaccines target the so-called spike proteins that cover the virus and help it invade human cells. The immune system can develop antibodies that latch onto spike proteins and stop the virus. A successful vaccine for the SARS-CoV-2 coronavirus would teach peoples immune systems to make antibodies against the virus without causing disease. Whole-Virus Vaccines Vaccines that modify the entire coronavirus to provoke an immune response. Inactivated and Live Attenuated Vaccines Most vaccines in use today incorporate an inactivated or weakened form of a virus that is not able to cause disease. When immune cells encounter them, they make antibodies. Making these vaccines means growing viruses and lots of them. Influenza vaccines are typically grown in chicken eggs, and other vaccines are grown in tanks full of floating cells. These procedures can take months to produce a batch of new vaccines. EXAMPLES: Conventional vaccines for influenza, chickenpox, measles, mumps and rubella all fall into this category. COMPANIES DEVELOPING SARS-COV-2 VACCINES: Sinovac and others. Genetic Vaccines Vaccines that use part of the coronaviruss genetic code. DNA Vaccines A number of experimental coronavirus vaccines dont deliver whole viruses. Instead, they deliver genetic instructions for building a viral protein. The protein can then stimulate the immune system to make antibodies and help mount other defenses against the coronavirus. One of these genetic approaches is known as a DNA vaccine. A circle of engineered DNA is delivered into cells'),
   Document(id='cd39d8bb-847b-44f6-9374-e2bb63b3d024', metadata={'source': 1, 'doc_index': 1, 'chunk_index': 2, 'total_chunks': 4}, page_content='. COMPANIES: Moderna, Pfizer and BioNTech, CureVac and others. Viral Vector Vaccines Vaccines that use a virus to deliver coronavirus genes into cells. Vaccines Using Adenovirus or Other Viruses Viruses are very good at getting into cells. Since the 1990s, researchers have been investigating how to use them to deliver genes into cells to immunize people against diseases. To create a coronavirus vaccine, several teams have added the spike protein gene to a virus called an adenovirus. The adenovirus slips into cells and unloads the gene. Because the adenovirus is missing one of its own genes, it cannot replicate and is therefore safe. EXAMPLES: Several virus vector vaccines are used to vaccinate animals against rabies and distemper. Johnson & Johnson has developed H.I.V. and Ebola vaccines using an adenovirus. Both have proven safe in humans and are now in efficacy trials. COMPANIES: Johnson & Johnson, CanSino, University of Oxford and others. Protein-Based Vaccines Vaccines that use a coronavirus protein or a protein fragment. Virus-Like Particle Vaccines Some vaccines are particles that contain pieces of viral proteins. They cant cause disease because they are not actual viruses, but they can still show the immune system what coronavirus proteins look like. EXAMPLES: The vaccine for HPV falls into this category. COMPANIES: Medicago, Doherty Institute and others. Recombinant Vaccines Yeast or other cells can be engineered to carry a viruss gene and spew out viral proteins, which are then harvested and put into a vaccine. A coronavirus vaccine of this design would contain whole spike proteins or small pieces of the protein'),
   Document(id='b84ce172-bf59-4b93-b856-acad027d65ef', metadata={'source': 1, 'doc_index': 1, 'chunk_index': 3, 'total_chunks': 4}, page_content='. COMPANIES: Medicago, Doherty Institute and others. Recombinant Vaccines Yeast or other cells can be engineered to carry a viruss gene and spew out viral proteins, which are then harvested and put into a vaccine. A coronavirus vaccine of this design would contain whole spike proteins or small pieces of the protein. EXAMPLES: This category includes some vaccines for shingles and hepatitis B. COMPANIES: Novavax and others. Sources: World Health Organization, National Institute of Allergy and Infectious Diseases, National Center for Biotechnology Information, NEJM'),
   Document(id='bf898b56-dcdc-44c4-be28-6d64107f9924', metadata={'source': 1, 'doc_index': 1, 'chunk_index': 1, 'total_chunks': 4}, page_content='. DNA Vaccines A number of experimental coronavirus vaccines dont deliver whole viruses. Instead, they deliver genetic instructions for building a viral protein. The protein can then stimulate the immune system to make antibodies and help mount other defenses against the coronavirus. One of these genetic approaches is known as a DNA vaccine. A circle of engineered DNA is delivered into cells. The cells read the viral gene, make a copy in a molecule called messenger RNA, and then use the mRNA to assemble viral proteins. The immune system detects the proteins and mounts defenses. Prototype DNA vaccines based on the spike protein protected monkeys from the coronavirus. EXAMPLES: DNA vaccines have been approved for veterinary cases such as canine melanoma and West Nile virus in horses. There are no approved DNA vaccines for use in humans, but researchers are running trials to see if they might be effective for diseases such as Zika and the flu. COMPANIES: Inovio and others. RNA Vaccines Some researchers want to skip DNA and instead deliver messenger RNA into cells. The cells read the mRNA and make spike proteins that provoke an immune response. The biotech company Moderna recently completed a small safety trial with eight volunteers that showed promising early results against the coronavirus. Both RNA and DNA vaccines can be produced more quickly than traditional methods. EXAMPLES: There are no approved RNA vaccines, but they are in clinical trials for MERS and other diseases. COMPANIES: Moderna, Pfizer and BioNTech, CureVac and others. Viral Vector Vaccines Vaccines that use a virus to deliver coronavirus genes into cells. Vaccines Using Adenovirus or Other Viruses Viruses are very good at getting into cells'),
   Document(id='7be148e7-b10d-4233-996d-f2828dbef8ca', metadata={'source': 3, 'doc_index': 3, 'chunk_index': 1, 'total_chunks': 4}, page_content='. The tests might also be used to identify potential donors of convalescent plasma, an approach in which blood plasma containing antibodies from a recovered individual is used to treat a Covid-19 patient, the F.D.A. said.The highly infectious disease has now killed nearly 70,000 people and sickened more than 1.1 million in the United States alone.While 12 companies have been given F.D.A. clearance to sell the antibody tests, many other products do not have agency authorization. The result has been a confusing landscape in which tests by established companies such as Abbott Laboratories, Cellex and most recently, Roche Diagnostics, are competing with unapproved tests made by unknown companies and sold by U.S. distributors with spotty track records. The F.D.A. has blocked imports of some antibody tests at the U.S. border, and has ordered some distributors to revise claims about what individuals can learn from them, or halt sales.House Democrats Raja Krishnamoorthi, of Illinois, and Rosa DeLauro, of Connecticut, have both criticized the agency for its handling of the matter as has Representative Lloyd Doggett, Democrat of Texas.The administrations original serology testing policy, which allowed tests on the market with no F.D.A. review, felt like an overreaction to the criticism they faced for their slow rollout of molecular tests, Mr. Krishnamoorthi said. But F.D.A. went too far, completely abrogating regulatory responsibility.Overseeing development of coronavirus tests has been rocky from the start, with President Trump and others urging the agency to relax rules for commercial tests')]},
 {'query': "Why did Judge Tanya Pratt reject Jared Fogle's legal arguments for early release?",
  'result': 'Judge Tanya Pratt rejected Jared Fogle\'s legal arguments for early release because she found his claims "frivolous" and stated that federal law specifically covers his crimes.',
  'source_documents': [Document(id='09d97abb-1a89-4d25-86ce-5b333bed59df', metadata={'source': 2, 'doc_index': 2, 'chunk_index': 0, 'total_chunks': 1}, page_content='Jared Fogle Shut Down By Judge In Bid for Early Release 1/22/2018 Jared Fogle got no love from the judge who sentenced him to 15 years in prison ... ruling his legal arguments were BS. Fogle had filed legal docs he prepared himself in the prison library, claiming Judge Tanya Pratt had no jurisdiction to even hear the criminal case because the sex crime charges required proof he traveled from one state to another to engage in sex acts with minors ... and he says everything was done in 1 state. Judge Pratt begged to differ, repeatedly calling Fogle\'s argument "frivolous," saying federal law specifically covers his crimes. The judge invited him to appeal to a higher court, but made it clear ... that dog don\'t hunt.'),
   Document(id='ee38622a-db4d-4dca-af81-1e5a661fc302', metadata={'source': 4, 'doc_index': 4, 'chunk_index': 1, 'total_chunks': 10}, page_content='.The libertarian position has become dominant on the right on First Amendment issues, said Ilya Shapiro, a lawyer with the Cato Institute. It simply means that we should be skeptical of government attempts to regulate speech. That used to be an uncontroversial and nonideological point. Whats now being called the libertarian position on speech was in the 1960s the liberal position on speech.And an increasingly conservative judiciary has been more than a little receptive to this argument. A new analysis prepared for The New York Times found that the Supreme Court under Chief Justice John G. Roberts Jr. has been far more likely to embrace free-speech arguments concerning conservative speech than liberal speech. That is a sharp break from earlier eras.As a result, liberals who once championed expansive First Amendment rights are now uneasy about them.The left was once not just on board but leading in supporting the broadest First Amendment protections, said Floyd Abrams, a prominent First Amendment lawyer and a supporter of broad free-speech rights. Now the progressive community is at least skeptical and sometimes distraught at the level of First Amendment protection which is being afforded in cases brought by litigants on the right.Many on the left have traded an absolutist commitment to free speech for one sensitive to the harms it can inflict.Take pornography and street protests. Liberals were once largely united in fighting to protect sexually explicit materials from government censorship. Now many on the left see pornography as an assault on womens rights.In 1977, many liberals supported the right of the American Nazi Party to march among Holocaust survivors in Skokie, Ill. Far fewer supported the free-speech rights of the white nationalists who marched last year in Charlottesville, Va'),

In [58]:
eval_dataset = gen_evaluate_dataset(testset3, responses_3)
eval_results3  = evaluate(
    dataset=eval_dataset, 
    metrics=metrics,
    llm=llm,
    embeddings=cached_embedding
)

Evaluating:   0%|          | 0/20 [00:00<?, ?it/s]

In [66]:
testset3.to_pandas()

,user_input,retrieved_contexts,reference,synthesizer_name
0,Are Elon Musk and Amber Heard currently back t...,"[Elon Musk, Amber Heard Something's Fishy On W...","Yes, the text suggests that Elon Musk and Ambe...",single_hop_specifc_query_synthesizer
1,What do most coronavirus vaccines target to he...,[Scientists are developing more than 100 coron...,Most vaccines target the spike proteins that c...,single_hop_specifc_query_synthesizer
2,Why did Judge Tanya Pratt reject Jared Fogle's...,[Jared Fogle Shut Down By Judge In Bid for Ear...,Judge Tanya Pratt rejected Jared Fogle's legal...,single_hop_specifc_query_synthesizer
3,What action did the FDA announce regarding cor...,[The agency had come under fire from members o...,The FDA announced that companies selling coron...,single_hop_specifc_query_synthesizer
4,How have conservative groups used the First Am...,[Credit...Jim Wilson/The New York TimesJune 30...,Conservative groups have used the First Amendm...,single_hop_specifc_query_synthesizer

In [72]:
testset3.samples[2].eval_sample.retrieved_contexts

['Jared Fogle Shut Down By Judge In Bid for Early Release 1/22/2018 Jared Fogle got no love from the judge who sentenced him to 15 years in prison ... ruling his legal arguments were BS. Fogle had filed legal docs he prepared himself in the prison library, claiming Judge Tanya Pratt had no jurisdiction to even hear the criminal case because the sex crime charges required proof he traveled from one state to another to engage in sex acts with minors ... and he says everything was done in 1 state. Judge Pratt begged to differ, repeatedly calling Fogle\'s argument "frivolous," saying federal law specifically covers his crimes. The judge invited him to appeal to a higher court, but made it clear ... that dog don\'t hunt.']

In [59]:
eval_results3

{'context_precision': 0.9400, 'context_recall': 1.0000, 'faithfulness': 0.9333, 'answer_relevancy': 0.8622}

In [64]:
eval_results3['faithfulness']

[1.0, 1.0, 0.6666666666666666, 1.0, 1.0]

In [65]:
responses_3[2]

{'query': "Why did Judge Tanya Pratt reject Jared Fogle's legal arguments for early release?",
 'result': 'Judge Tanya Pratt rejected Jared Fogle\'s legal arguments for early release because she found his claims "frivolous" and stated that federal law specifically covers his crimes.',
 'source_documents': [Document(id='09d97abb-1a89-4d25-86ce-5b333bed59df', metadata={'source': 2, 'doc_index': 2, 'chunk_index': 0, 'total_chunks': 1}, page_content='Jared Fogle Shut Down By Judge In Bid for Early Release 1/22/2018 Jared Fogle got no love from the judge who sentenced him to 15 years in prison ... ruling his legal arguments were BS. Fogle had filed legal docs he prepared himself in the prison library, claiming Judge Tanya Pratt had no jurisdiction to even hear the criminal case because the sex crime charges required proof he traveled from one state to another to engage in sex acts with minors ... and he says everything was done in 1 state. Judge Pratt begged to differ, repeatedly calling Fogle\'s argument "frivolous," saying federal law specifically covers his crimes. The judge invited him to appeal to a higher court, but made it clear ... that dog don\'t hunt.'),
  Document(id='ee38622a-db4d-4dca-af81-1e5a661fc302', metadata={'source': 4, 'doc_index': 4, 'chunk_index': 1, 'total_chunks': 10}, page_content='.The libertarian position has become dominant on the right on First Amendment issues, said Ilya Shapiro, a lawyer with the Cato Institute. It simply means that we should be skeptical of government attempts to regulate speech. That used to be an uncontroversial and nonideological point. Whats now being called the libertarian position on speech was in the 1960s the liberal position on speech.And an increasingly conservative judiciary has been more than a little receptive to this argument. A new analysis prepared for The New York Times found that the Supreme Court under Chief Justice John G. Roberts Jr. has been far more likely to embrace free-speech arguments concerning conservative speech than liberal speech. That is a sharp break from earlier eras.As a result, liberals who once championed expansive First Amendment rights are now uneasy about them.The left was once not just on board but leading in supporting the broadest First Amendment protections, said Floyd Abrams, a prominent First Amendment lawyer and a supporter of broad free-speech rights. Now the progressive community is at least skeptical and sometimes distraught at the level of First Amendment protection which is being afforded in cases brought by litigants on the right.Many on the left have traded an absolutist commitment to free speech for one sensitive to the harms it can inflict.Take pornography and street protests. Liberals were once largely united in fighting to protect sexually explicit materials from government censorship. Now many on the left see pornography as an assault on womens rights.In 1977, many liberals supported the right of the American Nazi Party to march among Holocaust survivors in Skokie, Ill. Far fewer supported the free-speech rights of the white nationalists who marched last year in Charlottesville, Va'),
  Document(id='0e2bb9f5-d4ab-4c4d-8a13-9ed022b6384f', metadata={'source': 4, 'doc_index': 4, 'chunk_index': 0, 'total_chunks': 10}, page_content='Credit...Jim Wilson/The New York TimesJune 30, 2018WASHINGTON On the final day of the Supreme Court term last week, Justice Elena Kagan sounded an alarm.The courts five conservative members, citing the First Amendment, had just dealt public unions a devastating blow. The day before, the same majority had used the First Amendment to reject a California law requiring religiously oriented crisis pregnancy centers to provide women with information about abortion.Conservatives, said Justice Kagan, who is part of the courts four-member liberal wing, were weaponizing the First Amendment.The two decisions were the latest in a stunning run of victories for a conservative agenda that has increasingly been built on the foundation of free speech. Conservative groups, borrowing and building on arguments developed by liberals, have used the First Amendment to justify unlimited campaign spending, discrimination against gay couples and attacks on the regulation of tobacco, pharmaceuticals and guns.The right, which had for years been hostile to and very nervous about a strong First Amendment, has rediscovered it, said Burt Neuborne, a law professor at New York University.The Citizens United campaign finance case, for instance, was decided on free-speech grounds, with the five-justice conservative majority ruling that the First Amendment protects unlimited campaign spending by corporations. The government, the majority said, has no business regulating political speech.The dissenters responded that the First Amendment did not require allowing corporate money to flood the political marketplace and corrupt democracy.The libertarian position has become dominant on the right on First Amendment issues, said Ilya Shapiro, a lawyer with the Cato Institute. It simply means that we should be skeptical of government attempts to regulate speech. That used to be an uncontroversial and nonideological point'),
  Document(id='d9687ca3-e89c-43c2-addd-fde6132c489b', metadata={'source': 7, 'doc_index': 7, 'chunk_index': 0, 'total_chunks': 4}, page_content='Fortnites parent company, Epic Games, had broken its contract with Apple, a federal judge found. The case goes to trial next year.Credit...Brian Finke for The New York TimesPublished Oct. 9, 2020Updated Sept. 10, 2021SAN FRANCISCO A federal judge ruled on Friday that Apple did not need to reinstate the popular video game Fortnite in its App Store, in a blow to Fortnites parent company, Epic Games, which is locked in an antitrust battle with the tech giant over its app store fees and rules.Judge Yvonne Gonzalez Rogers of the Northern District of California said in her ruling that Apples ban of the game could continue because Epic had violated its contract with Apple. There is significant public interest in requiring companies to adhere to contracts or resolve disputes through the normal course, she wrote.But Judge Gonzales Rogers also said that Apple could not ban Unreal Engine, Epics developer tools, from its platforms because of the potential significant damage to both developers and gamers who rely on the software.The mixed ruling showed the high cost of taking on a tech behemoth like Apple, even for an established company like Epic. The 116 million people who have accessed Fortnite through Apples systems will continue to be kept away while Epic and Apple prepare for a trial in the case, which is scheduled for May.An Epic spokeswoman said the company is grateful that Apple will continue to be barred from retaliating against Unreal Engine and our game development customers. Epic will continue developing for Apples platforms and pursue all avenues to end Apples anti-competitive behavior, she said'),
  Document(id='ee2af6e2-5c79-4bde-9c65-d7b53907933c', metadata={'source': 7, 'doc_index': 7, 'chunk_index': 3, 'total_chunks': 4}, page_content='.Smaller app makers, normally wary of angering the tech giants, have found strength in numbers. In September, more than a dozen of them, including the music streaming service Spotify, the dating service Match Group and the Bluetooth tracking device maker Tile, formed a nonprofit group called Coalition for App Fairness to push for changes to the app stores.In a hearing last month, Apple said it was willing to reinstate Fortnite to its app store before a trial if Epic would return to complying with its rules. Judge Gonzalez Rogers proposed an arrangement that would put Apples fees from Fortnite in an escrow account until after the trial. But Epic refused, arguing that doing so would be complying with a contract it views as unlawful.I didnt buy that argument before, Judge Gonzalez Rogers said in the hearing. Im not particularly impressed with it now.')]}